### ISSUE TITLE
PropTypes.oneOf relies upon stringification when using Symbols

### ISSUE THREAD

**Issue by aweary** [facebook/prop-types#10]
Original issue: https://github.com/facebook/react/issues/9181

**Comment by deadratfink** [comment]
Hi, is there any chance that this can be fixed quickly? I still experience this error when passing a `Symbol` instance to a `oneOf` PropType. This is in_ factoryWithTypeCheckers.js _ -> line 289 -> 

```
      return new PropTypeError('Invalid ' + location + ' `' + propFullName + '` of value `' + propValue + '` ' + ('supplied to `' + componentName + '`, expected one of ' + valuesString + '.'));
```

which can be fixed easily by `JSON.stringify` around `propValue`:

```
      return new PropTypeError('Invalid ' + location + ' `' + propFullName + '` of value `' + JSON.stringify(propValue) + '` ' + ('supplied to `' + componentName + '`, expected one of ' + valuesString + '.'));

```

**Comment by ljharb** [comment]
Using JSON is a bad idea because symbols stringify to null. Wrapping propValue in `String()` should be sufficient.

**Comment by deadratfink** [comment]
OK, looks like this depends on the environment running on, I just tried on Node.js 8.x during unit tests where I got

```
Failed prop type: Invalid prop `env` of value `42` supplied to `App.env`, expected one of ["development","shared","stage","production","test","storybook"].
```

when I provide `Symbol(42)` to the `env` property. As you can see the `42` is printed by `JSON.stringify`.

Of course, this should work out for the other environments:

- `... + String(propValue) + ...`
- `... + (typeof propValue === 'symbol' ? propValue.toString() : propValue) + ...`

Anyway, hope this gets fixed soon :smiley:
