### ISSUE TITLE
Standardize `func` and `bool` Proptypes

### ISSUE THREAD

**Issue by guillaumepotier** [facebook/prop-types#102]
Hi, I've searched a bit in the Readme and in the issues here, I did not find why we do not use `Proptypes.function` and `Proptypes.boolean` like we do for `object` (vs. `obj`), etc.

Why the shortnames? Are they reserved words? If not, it would be nice to create aliases maybe for these two ones no?

Thanks

**Comment by ljharb** [comment]
Yes, you can't do `const { function, bool } = PropTypes` in JS because they're reserved words.

**Comment by aweary** [comment]
Yeah, we won't likely change this API given the constraint @ljharb mentioned.
