### ISSUE TITLE
Whether it is necessary to add or / and / not ?

### ISSUE THREAD

**Issue by hustcc** [facebook/prop-types#105]
As we know the logical judgment contains `or`, `and`, `not`, and the combination between them.

And the API `oneOfType` is cname of `or`, but and / not is not exist.

e.g.

```js
propTypes = {
  // user id can not be admin or root.
  userName: PropTypes.not(PropTypes.oneOf(['admin', 'root'])),
}
```

In addition, API `apply` is also needed in some special circumstances, e.g.

```js
propTypes = {
  // users will save the user's id of this pagnation.
  users: PropTypes.and([ // users should be a array and the array.length <= 20
    PropTypes.arrayOf(PropTypes.string),
    PropTypes.apply(e => e.length <= 20), // page size is 20
  ])
}
```

So the four API may make it more powerful.

 - **and**
 - **or** / oneOfTypes
 - **not**
 - **apply**

In my webapp project, I need to check a variable's type and structure, so write one named [variable-type](https://github.com/hustcc/variable-type), and I think something can be done in prop-types here.

How do you feel?

**Comment by ljharb** [comment]
I have `and` and `or` in `airbnb-prop-types`; both have been very helpful for composition. I'm not sure if `apply` is necessary; that generic an API means you won't have helpful error messages besides "the predicate returned false".

"not" I haven't had a use case for, but I can see the logic.

**Comment by zxqfox** [comment]
Same here. Would be very helpful to have combinatoric operators like `and`, `or` and `not` to extend proptypes of components from libraries. 👍

**Comment by bradvogel** [comment]
+1 on adding 'and' to this package. My use case is to use PropTypes to assert both the `instanceOf()` and the `shape()` of an object: https://github.com/facebook/prop-types/issues/151

**Comment by ljharb** [comment]
See also #64.
