### ISSUE TITLE
Proptypes validation

### ISSUE THREAD

**Issue by rajur7** [facebook/prop-types#108]
It's about _feature_..
         The current behavior is, Proptypes are checking type of the parameters whatever the component receiving from parent component. 
        But `if Proptypes are also validate the values (real data) not only type of data it is receiving` then it can be useful for more specification to the values also, whenever we want to restrict the component to get the particular values it can be useful

**Comment by ljharb** [comment]
It can - you can compose your own custom propTypes to check both the type and the contents.
