### ISSUE TITLE
Why `PropTypes.node` forbids `true`?

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/prop-types#109]
It's a valid child: https://facebook.github.io/react/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored

**Comment by ljharb** [comment]
What would be the benefit of allowing something that someone might expect to render, but doesn't?

**Comment by Hypnosphi** [comment]
```
{someFlag || (
  <SomeComponent/>
)}

**Comment by aweary** [comment]
Hey @Hypnosphi, `PropTypes.node` should only allow data that will actually be rendered. If you try to render a boolean, nothing will happen.

```jsx
<div>{true}</div>
```

I don't recommend trying to render a boolean like you would a string or another component. If you want to conditionally render a component, use `null` when the component shouldn't render.

Hope that helps!

**Comment by Hypnosphi** [comment]
> PropTypes.node should only allow data that will actually be rendered

It allows `null`, `undefined`, and `false`. All of those render nothing.

**Comment by Hypnosphi** [comment]
My use case is not to render boolean directly, but use as a guard (see comment above). I believe that's exactly why they are valid children in React. Of course, I can refactor this to
```js
{!someFlag && (
  <SomeComponent/>
)}
```

Or even
```js
{someFlag ? null : (
  <SomeComponent/>
)}
```

I wonder why should I do that though

**Comment by ljharb** [comment]
A ternary is more explicit, since `&&` and `||` are value selection operators, not boolean logic operators.

**Comment by PiotrSiatkowski** [comment]
Wow, you didn't even try to answer his question.

**Comment by ljharb** [comment]
@PiotrSiatkowski the question was “why” and the answer is “because it’s more explicit”.
