### ISSUE TITLE
Feature request: warn when property not in propTypes is passed into component

### ISSUE THREAD

**Issue by aweary** [facebook/prop-types#11]
Original issue: https://github.com/facebook/react/issues/1587

**Comment by hakunin** [comment]
The best workaround right now is to use https://github.com/airbnb/prop-types

**Comment by crowdwave** [comment]
This meets my basic need which is just to know if the provided prop names don't match the expected prop names as defined in proptypes.

```
  componentDidMount() {
    let matchPropTypes = Object.keys(this.constructor.propTypes).every((a, index) => a === Object.keys(this.props)[index])
    if (!matchPropTypes) {console.log('propTypes do not match props', Object.keys(this.constructor.propTypes), Object.keys(this.props))}
  }
```

**Comment by Aprillion** [comment]
https://github.com/ReactTraining/react-router/issues/5114 is an example why this warning would by highly useful - ideally if the library authors could force it in their propTypes...

**Comment by AndersDJohnson** [comment]
Adding to @hakunin's answer in https://github.com/facebook/prop-types/issues/11#issuecomment-292865451, I think we'd use `forbidExtraProps` from https://github.com/airbnb/prop-types.

**Comment by mfru** [comment]
Is using AirBnB's proptypes still the recommended solution?

**Comment by coconup** [comment]
Here's an easy, DYI solution partially inspired by Airbnb's:

### utils/propTypesHelpers.js
```
import PropTypes from 'prop-types';

export function conditionalPropType(condition, message, fullMessageOverride = false) {
  if(typeof condition !== 'function') throw "Wrong argument type 'condition' supplied to 'conditionalPropType'";

  return function(props, propName, componentName) {
    const conditionResult = condition(props, propName, componentName);
    if (conditionResult) {
      const parsedMessage = typeof(message) === 'function' ? message(conditionResult, props, propName, componentName) : message;
      const defaultMessage = `Invalid prop '${propName}' '${props[propName]}' supplied to '${componentName}'. ${parsedMessage}`;
      return new Error(fullMessageOverride ? parsedMessage : defaultMessage);
    }
  }
}

export function forbidExtraProps(propTypes) {
  if (typeof propTypes !== 'object') {
    throw new TypeError('given propTypes must be an object');
  }

  const allowedPropKeys = Object.keys(propTypes);

  return {
    ...propTypes,
    _extraPropsCheck: conditionalPropType(
      props => {
        const unknownProps = Object.keys(props).filter(p => !allowedPropKeys.includes(p));
        return unknownProps.length > 0 ? unknownProps : false;
      }, 
      (unknownProps, _p, _pN, componentName) => `Unknown props found in component '${componentName}': ${unknownProps.join(', ')}.`,
      true,
    )
  }
}
```

### app/components/MyComponent.js
```
import { forbidExtraProps } from 'utils/propTypesHelpers';

[...]

MyComponent.propTypes = forbidExtraProps({
   ...
})
```

It'll give you a `conditionalPropType` helper as a bonus too.

**Comment by garfieldnate** [comment]
It took me a while to figure out that `Button` has no `style` attribute. I had assumed that it would die if I had passed in an unknown attribute, and I was puzzled by my styles not being applied to buttons.

**Comment by ljharb** [comment]
This seems done with #87 and `exact`.

**Comment by williamrjribeiro** [comment]
Apparently this feature is not yet implemented yet. See #263

**Comment by acnebs** [comment]
@ljharb `exact` is not working for me for this use-case.

**Comment by ZacharyRSmith** [comment]
If you don't want to change to airbnb's prop-types, this is best?: https://www.npmjs.com/package/prop-types-exact
