### ISSUE TITLE
Supporting ESM

### ISSUE THREAD

**Issue by tbranyen** [facebook/prop-types#111]
Working on native ESM integration with React and finding this to be a non-starter. The error I receive is:

```
🚨   Error: 'default' is not exported by node_modules/prop-types/prop-types.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
lib/component.js (2:7)
1: import process from './util/process';
2: import PropTypes from '../node_modules/prop-types/prop-types';
```

Would it be possible to get an ESM-compatible build of this module? It has zero dependencies so this should be really easy to switch to and then compile to ES5/require during the build step.

**Comment by ljharb** [comment]
I'm not sure why that should be necessary - a native ESM integration that can't pull in CJS modules is cut off from most of the internet :-/

**Comment by tbranyen** [comment]
@ljharb well it's how Chrome 61 works and it's fully connected :smiley: Node has a totally different implementation, but that's not really relevant to implementing a standard ES module to be loaded by a standard ES loader.

**Comment by ljharb** [comment]
How browsers work only applies after a build process runs on the server; if you bundle your entry point into an ESM, then browsers would be able to load the bundle just fine.

**Comment by frandiox** [comment]
@tbranyen I think [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) was precisely made for this, no need to change the whole internet.

**Comment by tbranyen** [comment]
@frandiox, that is condescending and not relevant to this issue. If Facebook doesn't want to use a standard format, that's fine. I'll just load it as UMD and grab the global. Eventually this module will change though. Just a matter of time.

**Comment by ljharb** [comment]
Are you suggesting they use an .mjs file? That’d be the standard format to follow.

**Comment by tbranyen** [comment]
> With the CommonJS require() and module.exports, it is easy to import a function that doesn’t really exist, and not realize that until you call it. However, tools like Rollup that natively support import and export syntax fail the build if you mistype a named import. After releasing React 16, we have converted the entire React source code to the ES Modules syntax.

https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html#migrating-to-es-modules

Looks like React went the route I suggested, which is great, I'm hoping now a contributor can comment on whether or not a PR would be accepted to land ESM.

**Comment by mishaor** [comment]
still nothing :(

**Comment by ljharb** [comment]
node does not yet support unflagged ESM; when it does, it will be appropriate to land it here; until then, it would be inappropriate to land it here (or in any npm package, really).

**Comment by weiluntong** [comment]
Hey @ljharb can you actually reiterate on your last comment? I'm sorry I don't understand what you mean by "land it here." I was just about to open an issue on "Refactoring CommonJS Imports and Exports to ES6 ESM imports and exports" when I found this issue. I thought changing the import export functionalities would be a good way for me to contribute and might be beneficial also for the same reasoning @tbranyen mentioned.

I also laid out ground work for what would be needed to change the import and exports, for further discussion on whether it's worth it or not. We'd need an extra babel plugin, "babel-plugin-transform-es2015-modules-commonjs", and we need to add `"sourceType": "module"` to the linter. I listed these mainly to have the information available for discussion though.

I mainly wanted to know if this is a good idea to follow through with, and what you mean by "land it here".

**Comment by ljharb** [comment]
I mean, prior to node supporting ESM without a flag, i don’t think any packages should publish anything but ES5 CJS, in “main”. Once node has that support, there theoretically will be a way to do dual packages (both cjs and ESM) and then prop-types can start shipping that.

**Comment by TrySound** [comment]
Node is not the only environment which consumes libraries. Browsers are able to run esm from node_modules with the help of unpkg.com (https://unpkg.com/jss@next?module). This is not ideal for prod but allows to not setup build tools for small experiments.

Bundlers provides much smaller bundles with ESM. For example webpack adds wrapper to every commonjs module to not deal with its dynamism. This blocks scope hoisting and prevents eliminating of unused code by terser.

`module` field is a good temporary solution for optimisation.

**Comment by weiluntong** [comment]
Not gonna lie, I personally think that since the code is being transpiled by Babel, it's good enough for the other non-supportive environments. As for Node, when they drop the flag in October (https://github.com/nodejs/modules/blob/master/doc/plan-for-new-modules-implementation.md), can I take that as a green light?

**Comment by ljharb** [comment]
@weiluntong *if* the flag is dropped then (i'm on the modules team so i'm pretty involved in the process), then yes, as long as there's a way to do dual packages, a PR would be welcome.

Note that Babel's transpilation is *not* necessarily good enough; it won't directly match parts of the spec, and its output is much larger than the handwritten code used here.

**Comment by TrySound** [comment]
FYI rollup generates clean commonjs similar to hand written.

**Comment by ljharb** [comment]
rollup violates the JS spec in a number of ways (or at least, has; it's possible they've fixed it now), i have no interest in adding rollup (altho other collaborators may disagree).

**Comment by TrySound** [comment]
> i don’t think any packages should publish anything but ES5 CJS, in "main"

Happily a lot of developers didn't follow this and now we have great optimisations and small bundles.

**Comment by ljharb** [comment]
Treeshaking works just as well on CJS, despite webpack not bothering to implement it, and treeshaking is only needed when imports are suboptimal anyways (ie, from manifest exports instead of deep-importing exactly what you need) - but this is all off topic.

**Comment by ryan-roemer** [comment]
As a related but somewhat separate observation, we could use this right now in modern browsers doing ESM backed by `unpkg` and we'd ❤️ to see this land (via `package.json:module` or whatever).

We're working more with ESM in the browser and most libraries with a `package.json:module` will work with `https://unpkg.com/PKG_NAME?module` flag. And while we have some control over using ESM-friendly versions of first level dependencies in our app code, lots of transitive dependencies take deps like `import PropTypes from 'prop-types';` which gets transformed to `import PropTypes from 'https://unpkg.com/prop-types@VERSION?modules';` when a dependency and in that use case it would be **great** to have ESM actually shipped as then everything magically works.

I'm sure "supporting ESM via how `unpkg.com` does it" isn't a top use case, but right now packages that _do_ ship `package.json:module` files completely work out of the box with modern browsers + ESM and I think it's a great start to what's likely the future for all of us... Thanks!!! 🙏

**Comment by ljharb** [comment]
The module field isn’t something that will ever work in node itself; tools that use it will instantly incur technical debt once node ships unflagged ESM.

**Comment by ryan-roemer** [comment]
I’m not tied to the module field, I’m open to really anything that allows prop-types to work in modern browsers right now with ESM 😀

**Comment by aduh95** [comment]
Unflagged ESM has landed on Node.js 13.2.0 and 12.17.0 (which will be released in the following weeks, although a [RC](https://nodejs.org/download/rc/v12.17.0-rc.0/) is already available). Would you reconsider adding the ESM syntax now?

**Comment by ljharb** [comment]
@aduh95 since you can import CJS already, it'd be a single `.mjs` file that provides the named exports, only for files that have more than one export.

However, there's no solution in ESM for conditionally synchronously importing things, so https://github.com/facebook/prop-types/blob/1c4077b7455e037bd8f81f48e9c51d60c972f8e9/index.js isn't really possible to represent with ESM.

**Comment by ljharb** [comment]
- node-native ESM, as well as transpiled ESM, can always consume CJS
 - authoring "no build tool" browser-consumable ESM is prohibitive
 - tree-shaking only provides a benefit if you're importing more than you need in the first place, which this package is not
 
I'm going to close this, but if there ever appears any concrete benefit to a package being anything besides "just CJS", we can reopen. I'm not currently aware of any such benefit, only downsides.

**Comment by brandonros** [comment]
Could this be revisited please so something like `https://unpkg.com/prop-types@15.8.1?moudle` can work?

```
<!doctype>
<html>
  <head>
  </head>
  <body>
      <script type="importmap">
      {
        "imports": {
          "d3": "https://unpkg.com/d3@7.6.1/src/index.js?module",
          "c3": "https://unpkg.com/c3@0.7.20/c3.esm.js",
          "preact": "https://unpkg.com/htm/preact/index.mjs?module",
          "preact-compat": "https://unpkg.com/preact-compat@3.19.0/dist/preact-compat.es.js?module",
          "prop-types": "https://unpkg.com/prop-types@15.8.1?module"
        }
      }
    </script>
    <script type="module">
      import c3 from 'c3'
      import { html, Component, render } from 'preact'
      import PropTypes from 'prop-types'
      import { findDOMNode } from 'preact-compat'
      console.log({
        c3
      })
    </script>
  </body>
</html>
```

prop-types not being available makes stuff like this kind of a dead end

**Comment by ljharb** [comment]
tbh that's a compelling use case - but then we'd have to figure out how to make the import of `react-is` and `object-assign` work, since import maps aren't a standard yet.

**Comment by ljharb** [comment]
@GervinFung prop-types is a CJS package, and if your bundler has trouble with those (they should work by default in a working node module bundler), then you'll need to configure and/or file an issue with your bundler.

**Comment by mnickolay** [comment]
I am using Vite and this package is causing an error of something like "prop-types does not provide an export named 'default'."
My solution to this was simply updating my vite.config file to include:
```js
export default {
    // rest of vite config...
    optimizeDeps: {
        include: ["prop-types"],
    },
}
```
