### ISSUE TITLE
No compatible version found : fbjs@^0.8.16

### ISSUE THREAD

**Issue by mehtayash** [facebook/prop-types#116]
This is happening from today only
**Steps:** 

npm install prop-types
npm ERR! Linux 4.4.0-89-generic
npm ERR! argv "/home/denimuser/.nvm/versions/node/v6.11.2/bin/node" "/home/denimuser/.nvm/versions/node/v6.11.2/bin/npm" "install" "prop-types"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: fbjs@^0.8.16
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.9.0-alpha.2, 0.9.0-alpha.1, 0.8.15, 0.8.14, 0.8.13, 0.8.12, 0.8.11, 0.8.10, 0.8.9, 0.8.8, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.8.0-alpha.3, 0.8.0-alpha.2, 0.8.0-alpha.1, 0.7.2, 0.7.1, 0.7.0, 0.6.1, 0.6.0, 0.5.1, 0.5.0, 0.4.0, 0.3.2, 0.3.1, 0.2.1, 0.2.0, 0.1.0-alpha.12, 0.1.0-alpha.11, 0.1.0-alpha.10, 0.1.0-alpha.9, 0.1.0-alpha.8, 0.1.0-alpha.7, 0.1.0-alpha.6, 0.1.0-alpha.5, 0.1.0-alpha.4, 0.1.0-alpha.3, 0.1.0-alpha.2, 0.1.0-alpha.1, 0.1.0-alpha.0, 0.0.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'prop-types'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:

**Comment by mehtayash** [comment]
Never mind. Some stale cache causes this.

**Comment by ollwenjones** [comment]
@mehtayash, I'm still seeing this. It's breaking local builds and our CI environment. Is the solution as simple as an `npm cache clean` ?

**Comment by ollwenjones** [comment]
`npm cache clean` did not do it for me...

**Comment by mehtayash** [comment]
@ollwenjones npm cache clean did not fix this. We use a local nexus server to cache npm repos and that had a 0.18.5 version. I just installed prop-types by removing that registry which proxies and installed directly from npm.

**Comment by ollwenjones** [comment]
@mehtayash ha! we're using nexus, too.  I see how your work-around would work for your workspace, but I don't see how it could fix a CI environment... there must be some way to make nexus behave itself for cases like this.

**Comment by mehtayash** [comment]
@ollwenjones Yes, that's still an issue. Have seen this happen before and it usually happens when a latest version is just released. In this case, it happened 15 hours ago. We had to clear our nexus cache manually last time. Still looking at options currently. Let me reopen this for now

**Comment by ljharb** [comment]
If it's an issue with nexus only, then this issue should be closed.

**Comment by ollwenjones** [comment]
@mehtayash yes, clearing the nexus cache manually is probably what will have to happen. Agree with @ljharb this should stay closed.

**Comment by mehtayash** [comment]
Thanks @ollwenjones. Will close this then.
