### ISSUE TITLE
Add support for `isPrototypeOf` checks

### ISSUE THREAD

**Issue by GianlucaGuarini** [facebook/prop-types#117]
At moment there is no test for Objects created via `Object.create`. 
Check the following example [demo](https://jsfiddle.net/gianlucaguarini/3rg43330/):

```js
const BAR_STRUCT = Object.seal({
  foo: 'foo'
})

const PROPS_STRUCT = Object.freeze({
  // of course it's not an instance of the bar struct, but what is it then? ¯\_(ツ)_/¯
  bar: PropTypes.instanceOf(BAR_STRUCT) 
})

const props = {
  bar: Object.create(BAR_STRUCT)
}

console.log(BAR_STRUCT.isPrototypeOf(props.bar))
PropTypes.checkPropTypes(PROPS_STRUCT, props, 'prop', 'Dummy')
```

Proposed change ```PropTypes.prototypeOf(whatever)```

Please let me know if you accept pull requests for this kind of feature

**Comment by ljharb** [comment]
You can do that with a custom propType, but using Object.create is both an edge case and not really a best practice at this point, so I don't think it should be a base type.

**Comment by GianlucaGuarini** [comment]
@ljharb ah sorry I didn't know `Object.create` was a bad practice. Can you please argument?

**Comment by ljharb** [comment]
Not bad, but not best. Copying objects with Object.assign or using class extends is generally better.

**Comment by GianlucaGuarini** [comment]
After a [long thread on Twitter](https://twitter.com/gianlucaguarini/status/913013240506052609) and many feedback it seems that this feature would be useful only to me 😄 
> You can do that with a custom propType, but using Object.create is both an edge case and not really a best practice at this point, so I don't think it should be a base type.

The @ljharb's opinion seems fair enough
