### ISSUE TITLE
PropTypes.node.required breaks in IE 11 on latest version

### ISSUE THREAD

**Issue by green-arrow** [facebook/prop-types#119]
I'm using [react-albus](https://github.com/americanexpress/react-albus) in my project, and in one of its components it defines `children` as `PropTypes.node.required`. In the case of this component (`Steps`), `children` is actually multiple components, each one needing to be a `Step` component:

```jsx
<Steps>
  <Step path="step1">
    // Stuff for step 1
  </Step>
  // Other Step components
</Steps>
```

After upgrading the `prop-types` package to `15.6.0` (from `15.5.10`), I started to get an error in IE 11. The error was complaining of an invalid prop type passed to `children`, and that it expected `ReactNode`.

I downgraded prop-types back to 15.5.10, and the problem went away.

I then upgraded prop-types back to 15.6.0, and the problem was still gone.

At this point I have no idea what happened as I can't consistently reproduce the issue, but I still wanted to post an issue here just in case anyone else is having the same problem or knows what might have caused this problem.

**Comment by ljharb** [comment]
This seems answered.
