### ISSUE TITLE
Immutable types?

### ISSUE THREAD

**Issue by th3fallen** [facebook/prop-types#122]
Im sure this has been brought up before but i dont see it in the past issues here.

It would be super nice to have something like `PropTypes.Map` `PropTypes.List` etc...

Alternatively, the ability to add custom prop-types at a higher level in the application would be nice and could resolve this issue.

**Comment by uniphil** [comment]
for Immutable.js types? There is [a library](https://github.com/HurricaneJames/react-immutable-proptypes) for that :)

**Comment by elazar** [comment]
> for Immutable.js types? There is a library for that :)

There is, but it requires an additional import for `ImmutablePropTypes`. Would be nice to have them be natively supported in `PropTypes`.

**Comment by ljharb** [comment]
Why would it make sense for PropTypes to natively support something that JavaScript doesn't?

**Comment by th3fallen** [comment]
I would argue because it is an extremely common library that is used and encouraged within the react community. which is the #1 consumer of this library. 

If I'm mistaking the intentions of this library I apologize but in my eyes this is a part of the react ecosystem as a whole and should support the same things.

Or at the very least be extensible at a higher level to support adding of custom props that can be used across multiple components without needing to redefine them in each component.

**Comment by ljharb** [comment]
I suspect it's not quite as common as you think.

A separate lib is the proper way to support it. Requiring/importing a custom lib for prop-types (like airbnb-prop-types) in each file you need it is a feature, not a burden.

**Comment by th3fallen** [comment]
Poor example but according to search trends it's extremely commonly searched for leading me to believe it's quite prevalent https://trends.google.com/trends/explore?q=react,react%20%2B%20immutable.js

But i could have just bastardized that trend so please excuse me if that's the case...

**Comment by uniphil** [comment]
Not to stray too far off topic, but something feels fishy about those trends to me. See [`Immutable.js`](https://trends.google.com/trends/explore?q=react,immutable.js) or [`react with immutable.js`](https://trends.google.com/trends/explore?q=react,react%20with%20immutable.js) next to `react`. Though, `immutable` does get 3.3M monthly npm downloads to `react`'s 5.9M though, which surprised me.

Still, `import { listOf } from 'react-immutable-prop-types'` has worked great for me. `prop-types` isn't even in `react` core any more and needs its own separate import. I have a lot of imports, but... well. javascript.

> Or at the very least be extensible at a higher level to support adding of custom props that can be used across multiple components without needing to redefine them in each component.

If it requires a registration system involving module-level state, it would be a big turn-off for me. One thing you could consider to cut down the imports though: re-export all the proptypes your app uses from a single module in your source tree. You can even name and re-use bigger composed proptypes there. And if you use webpack, you could set up an [`alias`](https://webpack.js.org/configuration/resolve/) to make importing them as easy as any third-party dep.

**Comment by ljharb** [comment]
Having more imports/requires in a file, when you need more things, is a *good thing*. Trying to reduce the number of imports without actually reducing the complexity of your code is a bad thing.

**Comment by icd2k3** [comment]
I agree with @ljharb - (using the app I'm working on as an example) we use `seamless-immutable` instead of `immutable` for props. So including immutable prop types in this package would be unnecessary bloat for us.

**Comment by ljharb** [comment]
That's only true if they use tree-shaking, which while it's a great thing to use, it's a terrible thing to *force* somebody to use.

**Comment by tommyalvarez** [comment]
@pigulla so we should go back to PropTypes.instanceOf method ?
