### ISSUE TITLE
False positive when using React.cloneElement

### ISSUE THREAD

**Issue by arempe93** [facebook/prop-types#123]
If `React.cloneElement` is used to pass required props to a component, prop-types still gives a validation error.

Here is a (contrived) example: https://jsfiddle.net/4qj8fygy/1

In this supplementary fiddle, we can see this occurs before the component even mounts: https://jsfiddle.net/q2g170ac/

**Comment by rhberro** [comment]
The Child component is being validated with no properties because of line ```27``` from this example https://jsfiddle.net/4qj8fygy/1. Maybe this is a React issue instead of the library?

**Comment by arempe93** [comment]
im sure that line `27` is a symptom of the problem. It seems to me that prop types are being validated on all JSX, instead of just JSX components that will actually be rendered by React. This is annoying because, even tho the above fiddle is clearly useless, there are legitimate uses for cloning required props down to children, or other props/variables.

Take the following example that uses `<Link />` from `react-router`


```js
import React from 'react'
import PropTypes from 'prop-types'
import { withRouter } from 'react-router-dom'

import Link from 'components/Link'

export const CourseLink = ({ component, match: { params: { courseId } }, to, ...rest }) => (
  React.cloneElement(component, {
    ...rest,
    to: `/courses/${courseId}/${to}`
  })
)

CourseLink.propTypes = {
  component: PropTypes.node,
  match: PropTypes.shape({
    params: PropTypes.shape({
      courseId: PropTypes.string.isRequired
    })
  }),
  to: PropTypes.string.isRequired
}

CourseLink.defaultProps = {
  component: <Link to='' />   // why add useless to=''? prop-types validation
}

export default withRouter(CourseLink)
```

there are other examples I have also, such as input wrappers passing down `name`, etc to `children`

**Comment by ljharb** [comment]
Whether it's rendered or not isn't relevant; propTypes are and *should* be validated when the element is created.

**Comment by arempe93** [comment]
Could you provide an example illustrating why that would be the case? I can't think of a reason to, unless it has something to do with React internals (with which I am largely unfamiliar)

**Comment by ljharb** [comment]
Imagine propTypes as runtime validation of constructor arguments, where the props are the arguments - `createElement` is what constructs the element. When you render it, or whether you ever do, is irrelevant - you'd still want to know that you'd passed invalid arguments at *construction* time, not at usage time.

**Comment by rhberro** [comment]
@ljharb you're right, the properties validation also happens when your components are being transformed into plain objects in a method called createElement inside ```React```.

**Comment by ljharb** [comment]
@arempe93 the issue is that `<Child />` is never valid, given your PropTypes. You'd have to pass `<Child name="this will be overriden" />` or something similar.

In other words, `name` is required whenever a `Child` is *created*, not just "whenever it's eventually rendered"

**Comment by arempe93** [comment]
@ljharb yes I think that much is clear, the props are validated when the component is created. My question was why they "*should* be validated when the element is created"

Im coming up blank, props are never used until a component is mounted; not even `constructor` is called until then. And its clear from my example + fiddles that elements can be created and never mounted, so why validate their props that are never used?

**Comment by ljharb** [comment]
@arempe93 because passing the wrong props is a *bug*, and bugs should be caught as early as possible.

**Comment by ljharb** [comment]
In other words, the creator of `<Child />` can't possibly know that it will be cloned and the proper prop added later; so the creator of that element is objectively wrong if they create it without its required `name` prop.

**Comment by arempe93** [comment]
i wouldn't say passing invalid props to `createElement` is necessarily a bug, because all it does it store an object. there's no way for that object to interact with the functionality of the component until it is mounted.

i do see the that 99% of the time props you pass to `createElement` and the eventual initial props are the same, but then `createElement` and mount would also usually happen almost simultaneously anyway, so you're not catching it any slower/quicker.

the way i perceive validation working in the current state is like so:

```js
const myProps = { foo: 'bar', name: 'Andrew' } // props are all good

<Child {...myProps} />



const myProps = { foo: 'bar' }  // error invalid props: missing 'name'

<Child {...myProps} name='Andrew' /> 
```

**Comment by ljharb** [comment]
OK, I'll phrase it another way.

Say that `<Child />` is passed around through 6 components before it ends up getting rendered. What happens if *that* component fails to clone it and add the `name` prop?

The user would end up seeing an error in *that* component - which they may not have even written - which would make it really hard for them to realize that `<Child />` was incorrect.

In other words, if you want a "partially completed" element, use `name => <Child name={name} />` instead of creating something that if not cloned *precisely correctly* before rendering will break.

**Comment by arempe93** [comment]
But that is a situation where it *is* invalid, and would be invalid no matter when validation took place. Because it was never given `name` at any point. In which case the user should see the message: `The prop 'name' is marked as required in 'Child'`, which should be fairly clear.

If the user had expected the parent components to pass down the prop, then they would realize they were mistaken and be required to provide the prop themselves. And if they merely forgot or were unaware of the requirement, then the validation message would be same as is now - prompting them to provide the prop to `<Child />` in some manner.

**Comment by ljharb** [comment]
Right, but the creator of the element *can not possibly know* that it will get a `name` later - the sole place they have the option to "provide the prop" is at element creation time, since the author of the one file is conceptually a different person than the author of the consuming file (even if they're the same person).

**Comment by arempe93** [comment]
yes, if they need to provide it, then they must provide it at create. that doesn't have a bearing on validation outcomes

```js
// author controlled
const myProps = { foo: 'bar' }  // create validation: invalid

// inside library component
<Child {...myProps} baz='zap' /> // mount validation: invalid, no name cloned in
```

the author cannot fix the cloning, but either validation would fail anyway. and if the author adds name to `myProps`, either validation would pass. so there is no difference in this situation between validation timings

the only situation i can think of that differs is what i illustrate in my examples, where you store an element and provide it props through cloning.

```js
const myProps = { foo: 'bar' } // create validation: invalid

<Child {...myProps} name='Andrew' /> // mount validation: valid!
```

**Comment by ljharb** [comment]
Right - cloning is the only case where it would ever make any sense to *allow* incomplete elements; and in general, cloning elements is something best avoided anyways.

**Comment by jameschao** [comment]
Thanks for this conversation. @ljharb I think you make a good point, and generally makes sense to me.

One place I can see `cloneElement` being used legitimately is in test helpers though (for example the suggested enzyme helper for `react-intl` https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#helper-function-1).

It's possible to rework the API to use a component type rather than the element itself, but it looks/feels more different from using JSX, so that's the drawback. In testing, it would be nice to use JSX, which is most clear, and also not have this warning.

It's a fringe case but just my two cents.

**Comment by mhelvens** [comment]
Apart from test-helpers, I also have a production use-case: A `<Form>` component that dynamically puts `value` and `onChange` props on its children so it can provide access to a composition of its children's values through its own props, e.g.:

```js
<Form value={this.state.obj} onChange={(obj) => { this.setState({ obj }) }}>
    <input name='fieldA' type='text' />
    <input name='fieldB' type='text' />
    <input name='enabled' type='checkbox' />
    <Form name='subForm'>
        {/* ... */}
    </Form>
</Form>
```

The whole point of `<Form>` is to provide a succinct notation for forms with lots of form fields, and to interact with their values as a single object. Doing things like `(props) => (<input name='fieldA' type='text' {...props}>)` would defeat the point.

I understand that React's current implementation cannot easily support this, but there are other legitimate use-cases. It's something to consider.

**Comment by ljharb** [comment]
This seems both answered, and is also something related to react itself, not this library.
