### ISSUE TITLE
Type-checking with oneOf and value could be undefined, but still warning for undefined

### ISSUE THREAD

**Issue by patw0929** [facebook/prop-types#127]
I would like to check a value with `PropTypes.oneOf`, and the value could be `undefined` and `''`. 
But it still show warning message even if I didn't put `isRequired` after `oneOf`, like this:

```javascript
export default class Test extends Component {
  static propTypes = {
    tab: PropTypes.oneOf(['aaa', 'bbb', 'ccc']),
  };

  static defaultProps = {
    tab: '',
  };
// ....
```

Warning:

```
Warning: Failed prop type: Invalid prop `tab` of value `` supplied to `Test`, expected one of ["aaa","bbb","ccc"].
```

So, should I also put `''`/`undefined` in `oneOf` array?
Thanks!

**Comment by ljharb** [comment]
There's not really a way to allow `undefined` but not `null`. If you can allow your values, as well as `undefined` and `null`, then it's just `PropTypes.oneOf('a', 'b', '')` (and yes, you'd need to include the empty string).

**Comment by patw0929** [comment]
Got it, thanks a lot 👍
