### ISSUE TITLE
How do I fit into the old version of react?

### ISSUE THREAD

**Issue by liukefu2050** [facebook/prop-types#128]
the new:
import PropTypes from 'prop-types';
the old:
import React, {
    PropTypes,
    Component,
} from 'react';
This style of writing is common in libraries of package.json
But I'd like to upgrade react to the latest version
What should I do?
thanks for help me!

**Comment by ljharb** [comment]
The new pattern should work with every version of React; at least down to 0.13.

**Comment by liukefu2050** [comment]
Thank you for your answer. I see the jscodeshift tool. Is there a similar way to change the code under node_modules? I want to use the latest react, and whether I can temporarily add "PropTypes" in the local react code

**Comment by ljharb** [comment]
You should not be changing dependencies directly; update and/or make PRs to them; they should all be using prop-types by this point.

**Comment by liukefu2050** [comment]
Well,I mean, is there a way to modify the react, because the local library so much without the use of "'prop-types'" in my project, pull request of all items, too much time, and some projects have been no maintenance

**Comment by ljharb** [comment]
I don't think there is; also I think if there's projects with no maintenance, they're not worth continuing to use - React 16 breaks a lot of dependencies.

In other words, if a project hasn't updated by now, it's probably a good idea to stop depending on it.

**Comment by liukefu2050** [comment]
OK，thinks a lot.

**Comment by qq912276337** [comment]
good
