### ISSUE TITLE
Examples of usage outside of React?

### ISSUE THREAD

**Issue by brandondurham** [facebook/prop-types#133]
The README seems to suggest prop-types can be used with “similar objects.” Is there an example of this anywhere?

**Comment by naffiq** [comment]
Isn't it [right in the end of the README file](https://github.com/facebook/prop-types#proptypescheckproptypes)?

**Comment by brandondurham** [comment]
I’m a fool. Thank you.

**Comment by naffiq** [comment]
You're welcome 👍
