### ISSUE TITLE
Use strict prop types structure as an interface of component.

### ISSUE THREAD

**Issue by pumanitro** [facebook/prop-types#138]
There should be a way to use only given propTypes in component otherwise it should cause error.

E.g. 

```
Test.proptTypes = {
  amount: PropTypes.number.isRequired
}
```
And when in parent I add more than defined props I should expect an error : 

```
//In parent
<Test amount={0} newNotExpectedProp={'x'} />
```

Should give me an error because of newNotExpectedProp.

**Comment by ljharb** [comment]
See https://npmjs.com/prop-types-exact (also in https://npmjs.com/airbnb-prop-types) 

Also, duplicate of #81, #84.

**Comment by ljharb** [comment]
`exact` now exists.
