### ISSUE TITLE
Shape should accept functions and arrays if they satisfy the shape

### ISSUE THREAD

**Issue by datenreisender** [facebook/prop-types#143]
If an array or function fulfills a shape, it should not be rejected by the shape proptype. E.g. with
```js
const f = () => {}
f.someProp = "value"
```
`f` should satisfy `PropTypes.shape({someProp: PropTypes.string.isRequired})` but is detected as a violation: 
```
Failed prop type: Invalid prop `f` of type `function` supplied to `component`, expected `object`.
```

**Comment by ljharb** [comment]
`shape` requires a plain object.

I built `withShape` in https://npmjs.com/airbnb-prop-types to cover this case.

**Comment by datenreisender** [comment]
I don’t see why shape requires a plain object, but I will give your `withShape` a try. Thanks for the pointer!

________________________________
