### ISSUE TITLE
Proptype validation error of window.parent when inside an iframe

### ISSUE THREAD

**Issue by astephenb** [facebook/prop-types#147]
When rendered inside of an iframe, a component with a prop that is a parent window object fails proptype validation with the following error:
`Blocked a frame with origin "other-origin" from accessing a cross-origin frame.`

I have reproduced this issue [here](https://github.com/astephenb/react-proptype-error). The error is originating from [factoryWithTypeCheckers.js#L466](https://github.com/facebook/prop-types/blob/77c62a719e496e459f6a16d62a84ab673f88f450/factoryWithTypeCheckers.js#L466)

**Comment by ljharb** [comment]
This is an inevitable and unavoidable consequence of trying to interact with a cross-realm object - why are you passing a parent window object as a prop?

In the repro case, you're using `PropTypes.shape` - in order to verify the shape, you have to have access to the object's properties, but that's impossible if it's cross-origin.

**Comment by astephenb** [comment]
Our app gets embedded as an iframe and we use the `postMessage` api to communicate to the host. I have ended up implementing a custom proptype validator, so this isn't a blocking issue, but it was something that came up after a react upgrade from 0.14.x to 15.6 so I thought I'd log a bug.

Anyways, feel free to close, mainly wanted to log this for posterity.

**Comment by ljharb** [comment]
You can pass the parent's `postMessage` function by itself, if you have permission to access it - there's no need to pass the entire window object around.

**Comment by astephenb** [comment]
Agreed. That's a good suggestion.
