### ISSUE TITLE
Feature request: use instanceOf() with shape() - chaining?

### ISSUE THREAD

**Issue by bradvogel** [facebook/prop-types#151]
Usually when using `PropTypes.instanceOf()`, I'd like to also check properties of the object instance. So I'm looking for something like:

```
MyComponent.propTypes = {
   myObject: PropTypes.instanceOf(MyObject).shape({
       myattribute: PropTypes.string.isRequired
   });
};
```

Though I suppose this could be implemented as a second parameter to `instanceOf()` to also assert the shape of the instance properties.

Is this something that you'd be interested in taking a PR to add?

**Comment by ljharb** [comment]
Using `and` from `airbnb-prop-types`, you'd do `and([PropTypes.instanceOf(MyObject), PropTypes.shape({ … })])`. Alternatively, using `withShape`, `withShape(PropTypes.instanceOf(MyObject), { … })`.

Perhaps `prop-types` could add an "and" combinator (#105)

**Comment by bradvogel** [comment]
Yes - you're right. Closing as a dup of https://github.com/facebook/prop-types/issues/105 since this covers the use case
