### ISSUE TITLE
Shape within Shape causes unexpected 'isRequired' - looks like a parsing error?

### ISSUE THREAD

**Issue by DisasterMan78** [facebook/prop-types#155]
If I declare a proptype as a shape within a shape, thus:

    export class DisplayProps extends Component {

      static propTypes = {
        displayProps: PropTypes.shape(
          PropTypes.shape({
            type: PropTypes.string,
            default: PropTypes.string,
          })
        ),
      };

      // ... rest of component

    }

An error is thrown:

    Warning: Failed prop type: The prop `displayProps.isRequired` is marked as required in `DisplayProps`, but its value is `undefined`.

If the inner shape is defined PRIOR to referencing it within the outer shape description, the error is not thrown:

    export class DisplayProps extends Component {

      static displayPropsShape = PropTypes.shape({
        type: PropTypes.string,
        default: PropTypes.string,
      });

      static propTypes = {
        displayProps: PropTypes.shape(
          this.displayPropsShape
        ),
      };

      // ... rest of component

    }

**Comment by ljharb** [comment]
That’s because shape takes an *object* - and the output of the inner shape has an `.isRequired` property.

I’m not sure why the second example doesn’t exhibit that behavior; if the static class fields transform is working properly, those two must be equivalent.

Either way, I’m not sure why you’d pass a shape into .shape?

**Comment by janjaap** [comment]
Experiencing the same issue, but within a different context. In my situation, I have a component (`CoreProvider`) that takes a `config` prop and I have a class (`Core`) that takes the same object as constructor parameter. In `Core` I'm manually validating the parameter with `checkPropTypes()`, like so:
```javascript
checkPropTypes(CoreProvider.propTypes.config, config, 'prop', 'Core');
```

When I'm running my tests and when not providing the `config` prop for `CoreProvider`, the following throws:
```Warning: Failed prop type: The prop 'config' is marked as required in 'CoreProvider', but its value is 'undefined'.
```

```javascript
// config is required
CoreProvider.propTypes = {
    children: PropTypes.node.isRequired,
    config: PropTypes.shape({
        routes: PropTypes.arrayOf(PropTypes.shape({
            ...
        })).isRequired,
        ...
    }).isRequired,
};
```

When I remove the `isRequired` flag for the `config` prop, when running my tests, I'm getting
```
Warning: Failed prop type: The prop `isRequired` is marked as required in `Core`, but its value is `undefined`.
```

`console.log(CoreProvider.propTypes)` gives me
```
{ children: [Function: bound checkType],
        config: { [Function: bound checkType] isRequired: [Function: bound checkType] } }
```

while (when `isRequired` flag is set), `console.log(CoreProvider.propTypes)` gives me
```
{ children: [Function: bound checkType],
        config: [Function: bound checkType] }
```

**Comment by luxx** [comment]
I am seeing more basic issue: .isRequired on a shape does nothing in prop-types 15.6.0. 

For example, consider this component invocation:
```
<ContentItem />
```

A failed prop type error for content.tags will correctly be raised when the `ContentItem.propTypes` are defined like so: 
```
ContentItem.propTypes = {
  content: PropTypes.shape({
    tags: PropTypes.array.isRequired
  })
}
```
However this renders without error:
```
ContentItem.propTypes = {
  content: PropTypes.shape({
    tags: PropTypes.array
  }).isRequired
}
```

Let me know if I should open a seperate issue for this. Thanks!

**Comment by ljharb** [comment]
I’d open up a separate issue for that; in my experience, it indeed would warn in that scenario.

**Comment by luxx** [comment]
Ah, oops, my issue can be disregarded. isRequired on a shape will do nothing if you supply a defaultProp :)

**Comment by ljharb** [comment]
The OP has been answered; @janjaap, I don't think that's the same problem (the console logs are correct, ftr), but if you're still having trouble, please file a new issue.
