### ISSUE TITLE
isDeprecated type in PropTypes

### ISSUE THREAD

**Issue by s-yadav** [facebook/prop-types#156]
Multiple time I have found the need of adding a deprecated warning on any specific prop. Currently, I do it on constructor method by checking if that is provided or not. 
I can't use customProp function as I still need that prop to be validated against a type (string, number, function) while marked as deprecated. (Not sure if there is existing way to do it)

@gaearon @acdlite . Does it make sense to add an isDeprecated marker similar to isRequired marker in the library?

Option 1. 
```js
{
  deprecatedAny: PropTypes.any.isDeprecated 
  deprecatedString:  PropTypes.string.isDeprecated.bind(null, 'This prop is marked as deprecated and will be removed on upcoming release.') //if you need to add custom warning
}
```

Option 2.
```js
{
  deprecatedAny: PropTypes.any.isDeprecated() //get the default warning 
  deprecatedString:  PropTypes.string.isDeprecated('This prop is marked as deprecated and will be removed on upcoming release.') //if you need to add custom warning
}
```
I can create a PR if this is something we want to add in the library.

**Comment by ljharb** [comment]
This exists as `restrictedProp` in https://npmjs.com/airbnb-prop-types - you'd do `and([PropTypes.string, restrictedProp()])`.

The issue, though, is that a deprecation warning and a propType warning are the same thing: a failure (because it logs to the console). i'm not sure there's any difference between banning a prop, and deprecating it.

**Comment by s-yadav** [comment]
@ljharb The primary difference is the log message we show for it. Also for me, restricted prop seems to require an immediate fix while deprecating is more liberal and require a progressive fix. Maybe we can add deprecatedProp() validator similar to restrictedProp.

But I see restrictedProp accepts a function to show a custom message (I had to read code though to know about it. It should be documented). Here adding an example if someone else lands here.
```js
import PropTypes from 'prop-types';
import {and, restrictedProp} from 'airbnb-prop-types';
....
SomeComponent.propTypes = {
 deprecatedStr:  and([PropTypes.string, restrictedProp((props, propName, componentName, location) => {
    return `The ${propName} ${location} on ${componentName} is deprecated.`
  })])
}
```

**Comment by ljharb** [comment]
Regardless of the message, how would React deliver it? `console.warn` and `console.error`s both fail tests, in a properly set up test suite.

**Comment by s-yadav** [comment]
Yes, I see custom validators are only allowed to return an error while deprecation is more  of a warning. Probably it allow returning a warning call or may be fbjs warning from `fbjs/lib/warning`. Not sure if that log trace.

**Comment by ljharb** [comment]
I think this can be achieved best with a custom validator, something like:
```js
function deprecated(validator) {
  return function deprecated(props, propName, ...rest) {
    if (props[propName] != null) {
      console.warn(`${propName} is deprecated`);
    }
    return validator(props, propName, ...rest);
  }
}
```
and you'd use it like:
```js
Foo.propTypes = {
  deprecatedString: deprecated(PropTypes.string),
};
```

**Comment by AndyWright-ct** [comment]
Is this still a valid / recommended method?
