### ISSUE TITLE
PropTypes boolean validation bug?

### ISSUE THREAD

**Issue by embpdaniel** [facebook/prop-types#157]
In my current project I want to pass a "config" object to my component which looks like this:

`{isReady: true}`

 To validate this object I create a prop type like this:

```javascript
MyComponent.propTypes = {
  config: PropTypes.objectOf(
     PropTypes.shape({
         isReady: PropTypes.bool
  }))
}
```

Then I pass a config object to the component:
`<MyComponent config={{isReady: true}}/>`

This produces a prop types warning:

`Warning: Failed prop type: Invalid prop 'config.isReady' of type 'boolean' supplied to 'MyComponent', expected 'object'.`

logging the prop on the console confirms the config object is passing a boolean, yet React thinks I have defined a prop type of object type. I'm confused.

I am using React `16.2.0`, React Native `0.52.0`, and PropTypes `15.6.0`

Here is a code sandbox link with an example: https://codesandbox.io/s/3r17px8n0m

**Comment by ljharb** [comment]
You want just `config: PropTypes.shape({ isReady: PropTypes.bool })`. What you have in the OP is an object whose *values* match "an object with a config key matching this shape"
