### ISSUE TITLE
it must be a function, usually from the `prop-types` package, but received `boolean`

### ISSUE THREAD

**Issue by MichaelBieniek** [facebook/prop-types#159]
Isn't PropTypes.bool supposed to be a function?
If I mark a parameter 
`static propTypes = {
	myProp: PropTypes.bool,
}
`
I get "it must be a function, usually from the `prop-types` package, but received `boolean`", since PropTypes.bool is not a function.

I'm using prop-types@15.6.0

**Comment by ljharb** [comment]
Can you share your entire code and the entire error message?

**Comment by MichaelBieniek** [comment]
My apologies. The error was not with the component above, but with a component which was imported. The imported component had an erroneous propTypes definition: `noToolTip: PropTypes.bool = false`, which was in fact the culprit. Thanks for the quick response - this is a non-issue.
