### ISSUE TITLE
TextInput: prop type `style` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

### ISSUE THREAD

**Issue by farid-ouachrar** [facebook/prop-types#163]
Hi guys, I'm getting this warning on every textinput in my app.
versions : 
prop-types: 15.6.0
react-native: 0.52.2
expo: 23.0.4

![image](https://user-images.githubusercontent.com/20015003/36533749-75719606-17bc-11e8-89bf-d6ab3f7b05e7.png)

**Comment by ljharb** [comment]
What’s TextInput.propTypes look like.

**Comment by farid-ouachrar** [comment]
@ljharb There is no TextInput.propTypes in the code

**Comment by ljharb** [comment]
Something must be assigning it, otherwise you wouldn’t get this error. Please share the code for TextInput?

**Comment by farid-ouachrar** [comment]
here's the snippet :
`render(){
       let {agentName, password} = this.state;
        let {checked_login} = this.props;
    return (
            <View style={styles.container}>
                <KeyboardAvoidingView behavior="padding" style={{flex: 0.6, alignItems: 'center'}}>
                    <TextInput 
                      placeholder="Agent name" 
                      value={agentName} 
                      onChangeText={(agentName) => this.setState({agentName})} 
                      underlineColorAndroid="rgba(0,0,0,0)" 
                      style={styles.input}
                    />
                    <TextInput 
                      placeholder="Password" 
                      secureTextEntry 
                      keyboardType="numeric" 
                      value={password} onChangeText={(password) => this.setState({password})} 
                      underlineColorAndroid="rgba(0,0,0,0)" 
                      style={styles.input}
                    />
                    <TouchableOpacity onPress={() => this.handleConfirmation()} style={styles.loginButton}>
                        <Text style={{color: 'white'}}>Login</Text>
                    </TouchableOpacity>
                </KeyboardAvoidingView>
            </View>
        )
    }
}

Login.propTypes = {
    error: PropTypes.string,
    checked_login: PropTypes.bool
}`

**Comment by ljharb** [comment]
That’s the Login component. I need to see the TextInput component.

**Comment by farid-ouachrar** [comment]
That's a react-native component.

**Comment by ljharb** [comment]
Interesting, not sure then.

**Comment by farid-ouachrar** [comment]
alright thank you.

**Comment by mayankbaiswar-CSE** [comment]
@farid-ouachrar use ViewPropTypes.style as prop-types.

**Comment by Podiya** [comment]
caching issue i guess. reload expo few times. then it will remove. what i did was 
`static propTypes = {
    text: PropTypes.string.isRequired
  }` 

to 

`static propTypes = {
    text: PropTypes.string
  }`

with out "isRequired" then reload. warning disappear. 

again add  "isRequired" worked fine.

**Comment by coljung** [comment]
@Podiya that is REALLY weird.

I also removed the 'isRequired', reloaded the page, then added the 'isRequired' back, and now the warnings are gone.

**Comment by ArshAgarwal28** [comment]
@Podiya where did you make this change? I am getting this error with react-native-calendar library.

**Comment by prem-pachouri** [comment]
Make sure you have import PropTypes like below

import PropTypes from 'prop-types';

**Comment by arvindsuriyaa** [comment]
Hi, Im having the same issue, here. since its a react native component.. we are quite unsure why this is happening in the first place..
