### ISSUE TITLE
Version 15.6.1 is on npm but not in github

### ISSUE THREAD

**Issue by jharris4** [facebook/prop-types#164]
I just saw that `15.6.1` was published to npm, but the `package.json` here on github still says `15.6.0`.

It's kind of hard to know what changed! :-)

**Comment by aweary** [comment]
@jharris4 nothing has changed 🙃 it was just released to fix a license header issue reported in #162. I just pushed the release commit now.

**Comment by jharris4** [comment]
Great thanks!
