### ISSUE TITLE
15.6.1 changelog?

### ISSUE THREAD

**Issue by jalada** [facebook/prop-types#165]
Hello! There's no CHANGELOG entry for the latest release. What are the changes?

**Comment by virgofx** [comment]
:+1: Agreed. Devs love to read the changelogs prior to upgrading. This also goes for listing releases. Until this release there were none in Github - just NPM (very annoying)

**Comment by aweary** [comment]
See https://github.com/facebook/prop-types/issues/164, there were no changes.

**Comment by aweary** [comment]
I've updated the CHANGELOG in https://github.com/facebook/prop-types/commit/7cc8c81d3aed103757f87f02a19baa16fe101bec
