### ISSUE TITLE
CDNJS 15.6.1 Release Not working

### ISSUE THREAD

**Issue by virgofx** [facebook/prop-types#166]
CDNJS returns a 404 not found for the 15.6.1 files. 15.6.0 works.

Not sure if the issue is on the CDNJS side or here. 
[Referenced CDNJS issue](https://github.com/cdnjs/cdnjs/issues/12560)

**Comment by aweary** [comment]
The package was published without issue and unpkg picked it up correctly. Seems like it's solely a CDNJS issue.

**Comment by virgofx** [comment]
Thanks - Will future releases be published in similar format or previous? Just curious if changes need to be made on the CDNJS side to support new release format?

**Comment by aweary** [comment]
There haven't been any changes to the release format, and I don't foresee us changing it in the near future.
