### ISSUE TITLE
A philosophy of redundancy

### ISSUE THREAD

**Issue by threecity** [facebook/prop-types#173]
Please don't be mad at me, I know this isn't a bug, but wouldn't it really help the case for propTypes to stick around if there was a more streamlined standard for approaching PT validation, because the beginner-level approach is really only smart if you're exclusively validating your container level and don't care about its components.

If devs were simply taught that you set up your propTypes APART from the React component, the way normalizr teaches you to set up your schemas apart from your app code, then I think those much smarter than me can scale the approach even further.

Something like this (a "prop shop" if you will (you don't have to)):

```js
import PT from 'prop-types'

const {arrayOf, shape, string} = PT

export const isRequired = (item, is) => is ? item.isRequired : item

export const isString = is => isRequired(string, is)

export const countryCode = isString
export const countryName = isString

export const countryByCode = is => isRequired(
  shape({
    code: countryCode(true),
    name: countryName(true),
  }), is
)

export const countriesByCode = is => isRequired(
  arrayOf(countryByCode()), is
)

export const countries = is => isRequired(
  shape({
    byCode: countriesByCode(true),
  }), is
)

export const assets = is => isRequired(
  shape({
    countries: countries(true),
  }), is
)

export default assets
```

Then all it takes is this:
```js
import assets from './assets'
Component.propTypes = {
  assets: assets(true),
}
```
or
```js
import {countries} from './assets'
Component.propTypes = {
  countries: countries(true),
}
```

I have to give new hires the red pill and re-teach them how to validate propTypes, a little help would be much appreciated.

Great job on everything you guys are awesome forever

**Comment by threecity** [comment]
**Side note:** When I say possibly scaling this approach, I mean a way to manually toggle the `isRequired` flag for each prop like this:
```
assets(true, {
  countries: {
    byCode: false,
  },
})
```

**Comment by troglotit** [comment]
Also, there could be some higher-order function, which takes a function and pro-types object, and validates arguments on that.

**Comment by ljharb** [comment]
I'm not sure what's actionable here; happy to reopen if this is made clear.
