### ISSUE TITLE
style类型该怎么写？

### ISSUE THREAD

**Issue by zhengxuanyi** [facebook/prop-types#175]
tabStyle: PropTypes.style,
tabsContainerStyle: PropTypes.style,

会报警告

**Comment by ljharb** [comment]
I’m not sure what you’re asking, but “style” could mean many things depending on the component it applies to, and is probably best left up to your CSS framework of choice.

**Comment by waiwaiku** [comment]
PropTypes.object

**Comment by ljharb** [comment]
This seems answered.
