### ISSUE TITLE
oneOf doesn't warn about null values

### ISSUE THREAD

**Issue by WickyNilliams** [facebook/prop-types#176]
Given the following component:

```js
const Test = ({ foo, bar }) => <div>{foo}:{bar}</div>;

Test.propTypes = {
  foo: PropTypes.oneOf(["a", "b"]),
  bar: PropTypes.oneOf(["c", "d"]).isRequired
};
```

Which gets rendered as: `<Test foo={null} bar={null} />`

I would expect a warning for both props, but only `bar` gets logged. Here's a test case https://codesandbox.io/s/24k0vpxj3p

Is this a bug or intentional?

**Comment by WickyNilliams** [comment]
Yeah, but then `defaultProps` doesn't consider `null` unset. It's inconsistent

**Comment by WickyNilliams** [comment]
Example: I have a component with default props, so a prop is not required to be passed. However, passing `null` means the default prop isn't supplied, breaking the component but without a warning

**Comment by ljharb** [comment]
The default choice mirrors language default arguments. Treating `null` and `undefined` as the same mirrors community convention.

This isn’t a bug; if you have a non-required propType, it’s either `null`, `undefined`, or something that matches the propType.

**Comment by WickyNilliams** [comment]
It's just confusing/unexpected in this case because you've specified the exact set of possible values, of which null is not included.

But fair enough, not going to argue over it. Thanks for the insight!
