### ISSUE TITLE
installation of prop-types removes node modules

### ISSUE THREAD

**Issue by isabellachen** [facebook/prop-types#177]
Using `create-react-app` I created a react app and thereafter installed prop-types. As I installed it, I realised it was deleting a huge amount of folders and files from my node_modules folder. After changing some text in a h1 element, the app threw an error `Module build failed: Error: ENOENT: no such file or directory, open '/Users/isabellachen/Developer/tutorials/wtf/node_modules/react-scripts/config/polyfills.js'` 

Looks like more than half the folders in my node-modules is gone. 

I thereafter removed prop-types from package.json and `npm i` to reinstall all the dependencies and my app is up and running again.

**Comment by yasircse** [comment]
same here...I also create App using "create-react-app". later installed "prop-types" once prop-types installed, it gave me following message
+ prop-types@15.6.1
added 3 packages, removed 1203 packages and updated 15 packages in 35.944s

Note "prop-type" installation caused me to loose 1203 packages out of node_modules .....My threw me error as well.

I don't know why prop-types is causing this problem.

"temporary solution"  install prop- types....then delete the whole "node_modules"  folder...and run the command ...yarn install or npm install.........

**Comment by ljharb** [comment]
Is this still an issue? I'm not sure how it could be related to this library specifically (as opposed to a bug in npm or yarn themselves)

**Comment by amitnitjsr** [comment]
delete node modules 
npm install
npm i prop-types
