### ISSUE TITLE
Security Problem in prop-types@15.6.1

### ISSUE THREAD

**Issue by saostad** [facebook/prop-types#182]
Hi, Today I checked my application with Snyk.io and I got this error:

    > ✗ Medium severity vulnerability found on ua-parser-js@0.7.17
> 
>         desc: Regular Expression Denial of Service (ReDoS)
>         info: https://snyk.io/vuln/npm:ua-parser-js:20180227
>         from: kusa-timesheet-webapp-client@0.1.0 > antd@3.4.5 > rc-dropdown@2.1.2 > rc-trigger@2.3.4 > rc-animate@2.4.4 > prop-types@15.6.1 > fbjs@0.8.16 > ua-parser-js@0.7.17
>         Fix: None available. Consider removing this dependency.

**Comment by fczuardi** [comment]
as a workaround, if using yarn, you can add the following to your package.json:

```
"resoltions": {
  "ua-parser-js": "^0.7.18"
}
```

**Comment by fczuardi** [comment]
but a PR updating this dependency on prop-types should be simple to write too, we should submit one...

**Comment by fczuardi** [comment]
actually, the patch should be submitted to fbjs, I dont know if there is an open issue for this on that project yet https://github.com/facebook/fbjs/issues

**Comment by fczuardi** [comment]
:point_up: opened

**Comment by ljharb** [comment]
fbjs is no longer a dependency of this module.
