### ISSUE TITLE
Generate JSON schema from PropTypes

### ISSUE THREAD

**Issue by francisypl** [facebook/prop-types#184]
Is this a feature? http://json-schema.org/
or another schema language

**Comment by ljharb** [comment]
PropTypes are much much more powerful and expressive than json schema is capable of expressing; you could easily make a jsonschema-based validator propType yourself, tho.

**Comment by francisypl** [comment]
Yea I'm probably going doing that. JSON based schema definitely won't have feature parity with proptypes but I have a use case where i need to express Component proptypes in json format.

**Comment by ljharb** [comment]
This is also related to #60.

Closing as answered.
