### ISSUE TITLE
Conditional PropTypes

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/prop-types#186]
is there a way to say, if I have `propA`, `propB` is required?

**Comment by ljharb** [comment]
Use requiredBy from https://github.com/airbnb/prop-types

**Comment by ljharb** [comment]
@lifeiscontent use `or` and combine it with two requiredBys.

**Comment by dryoma** [comment]
Why was this closed, I wonder? Seems like a feature that is natural for the package and shouldn't require third party libs.

**Comment by lifeiscontent** [comment]
@dryoma i realized a custom validator is pretty easy to create

**Comment by joshuapinter** [comment]
### Use `isRequiredIf`.

There is a [PR][1] from 4 years ago by @evcohen that added `isRequiredIf` to the PropTypes library. Unfortunately, even at that time they were putting the PropTypes library in maintenance mode and would not merge it in.

The [company I work for][2] still uses PropTypes and so we forked the `master` branch of the PropTypes library and added this functionality in.

So now you can do something like this: 

```js
ariaLabel: PropTypes.string.isRequiredIf( props => props.children )
```

Super clean and minimal. 

Feel free to use [our fork][3] in your own project by updating your `package.json` with the following: 

```json
"prop-types": "github:cntral/prop-types#isRequiredIf"
```

_NOTE: It does not take a boolean param, only a function that is passed the props and needs to return a boolean._


  [1]: https://github.com/facebook/react/pull/5933
  [2]: https://www.cntr.al/
  [3]: https://github.com/cntral/prop-types/tree/isRequiredIf

**Comment by ljharb** [comment]
@joshuapinter airbnb-prop-types may also be helpful.
