### ISSUE TITLE
Unnecessary dependencies from fbjs

### ISSUE THREAD

**Issue by Taylor123** [facebook/prop-types#188]
Is it necessary for this package to be dependent on all of [fbjs](https://github.com/facebook/fbjs)? I understand that it can make things easier for development, but I ran into an issue due to fbjs' dependency on [isomorphi-fetch](https://github.com/matthew-andrews/isomorphic-fetch).

For the issue i ran into, see https://github.com/matthew-andrews/isomorphic-fetch/issues/125

**Comment by the-spyke** [comment]
A have a similar issue, but with `core-js`:

```
└─┬ prop-types@15.6.1
  └─┬ fbjs@0.8.17
    └── core-js@1.2.7 
```

Even if all my other packages depend on `core-js@2.x`, `npm` continues to put `core-js@1` from `fbjs` into the root `node_modules`, what leads to missing polyfills.

**Comment by ljharb** [comment]
fbjs is no longer a dependency of this package.
