### ISSUE TITLE
Read to compare propType, how to check Array?

### ISSUE THREAD

**Issue by fbacker** [facebook/prop-types#189]
Can't figure out how to read propType arrays from a component. string, number, bool works fine.

Look at example index.js at line 31
[![Edit PropTypes validate - compare](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/92n7w5lw24)

**Comment by ljharb** [comment]
I don't think there's any way to check that.

**Comment by Pimm** [comment]
Hi @fbacker,

It seems the issue you are having is caused by some validators being a single ‒ cached ‒ function, while other functions are created on the fly.

Specifically:
```javascript
PropTypes.string === PropTypes.string; // This is true
PropTypes.arrayOf(PropTypes.string) === PropTypes.arrayOf(PropTypes.string); // This is false
```

This is not a bug. You are using `prop-types` in a way for which it is not designed. I think your best bet would be to change your design slightly.

#### Use JSON instead of manually converting the props

Instead of writing
```html
data-varstring="hello"
data-numstring="23"
data-arrstring="value1,value2,value3"
data-boolstring="true"
```
you could write
```html
data-varstring="\"hello\""
data-numstring="23"
data-arrstring="[\"value1\",\"value2\",\"value3\"]"
data-boolstring="true"
```

This way, you can `JSON.parse` the `.nodeValue`.

#### Add prop conversion functions to the component

In addition to the `.propTypes`, you could add a `.propConverters` map:
```javascript
Hello.propConverters = {
  varstring: input => input,
  numstring: input => parseInt(input, 10),
  arrstring: input => input.split(','),
  boolstring: input => 'true' == input || 'yes' == input || '1' == input
};
```

And then you can call `reactComponent.propConverters[id]` passing the `.nodeValue`.

Note: I am not a maintainer of this package.

**Comment by fbacker** [comment]
using EPI to load components and want editors to change values. So the JSON is a nice idea but won't work for my case.

So probably this will be the solution. If it's an array the variable needs to start with 'arr'. 

````js
function variableConvert(id, value, propType) {
  const defaultValue = value;
  if (value !== null) {
    if (propType !== undefined) {
      if (propType === PropTypes.number) {
        value = parseInt(defaultValue, 10);
        if (value.toString() === defaultValue) return value;
        return defaultValue;
      } else if (propType === PropTypes.bool) {
        value = defaultValue.toString().toLowerCase();
        if (value === 'true' || value === 'yes' || value === '1') {
          return true;
        }
        return false;
      } else if (propType === PropTypes.string) {
        return value;
      }
    }
    // DONT LIKE
    // array
    if (id.length > 2 && id.indexOf('arr') === 0) {
      value = defaultValue.split(',');
      if (value.length > 0) return value;
    }
  } else if (value === '') {
    // only attribute, no value
    return true;
  }

  return defaultValue;
}
````

**Comment by fbacker** [comment]
I'm giving up to use proptypes to convert value when loading my components.
I notice when doing a production build if (propType === PropTypes.number) { will take all values.

So back to my original solution
````js
function variableConvert(id, value) {
  const defaultValue = value;
  if (value !== null) {
    // number
    value = parseInt(defaultValue, 10);
    if (value.toString() === defaultValue) return value;
    // boolean
    value = defaultValue.toString().toLowerCase();
    if (value === 'true' || value === 'yes' || value === '1') {
      return true;
    } else if (value === 'false' || value === 'no' || value === '0') {
      return false;
    }
    // array
    if (id.length > 2 && id.indexOf('arr') === 0) {
      value = defaultValue.split(';');
      value = value.filter(e => e);
      if (value.length > 0) return value;
    }
  } else if (value === '') {
    // only attribute, no value
    console.log('parse bool default', id, value);
    return true;
  }
  return defaultValue;
}
````

**Comment by ljharb** [comment]
This seems answered.
