### ISSUE TITLE
Enable CI testing

### ISSUE THREAD

**Issue by aweary** [facebook/prop-types#19]
Currently, there is no CI setup for running the unit tests against PRs. There should be!

**Comment by joefraley** [comment]
I could set this up if you want. Are there any opinions about preferred CI frameworks? Travis is good, and free for public repos

**Comment by ljharb** [comment]
Definitely travis-ci.

Probably jest, since Facebook's internal tests for this almost certainly use jest.

**Comment by joefraley** [comment]
@ljharb it looks like lots of tests are already in place, i think this issue is just a question of having them run for any new branches/prs

**Comment by realityking** [comment]
It would be great to get this done. Tests actually seem to be broken right now, see #129
