### ISSUE TITLE
Suppressing a PropType warning

### ISSUE THREAD

**Issue by Norbo11** [facebook/prop-types#192]
I'm using a third-party library which as a wrongly-defined proptype in one of their components. I now get a very annoying PropType warning in the console. What would be the best way to suppress this warning?

**Comment by ljharb** [comment]
File an issue/PR on that third-party library, or use a different library?

**Comment by cj4luv** [comment]
i have same things 

plz any solutions?

**Comment by ljharb** [comment]
This is answered; the solution is to fix the propType definition that's causing a problem.
