### ISSUE TITLE
instanceOf should follow prototype chain?

### ISSUE THREAD

**Issue by wmertens** [facebook/prop-types#195]
It can happen that some prop is actually an instance of a subclass of what is expected by `instanceOf`. For example, with HMR, some classes are wrapped.

For these cases it would be nice if the prototype chain is followed.

I see two possibilities:

1. adjust `instanceOf` to check `Object.getPrototypeOf(value)` recursively
2. add another predicate for this case

The nice thing about 1. is that it will fix spurious warnings when using HMR.

**Comment by ljharb** [comment]
`instanceOfSubclass instanceof ParentClass` is already true; I'm not sure what needs to change here.

The issues with HMR are that it breaks object identity, and it can't be fixed except in the HMR tool itself.
