### ISSUE TITLE
How does isNode typecheking work with boolean types?

### ISSUE THREAD

**Issue by ottodevs** [facebook/prop-types#199]
https://github.com/facebook/prop-types/blob/cfc7f43af3d74978ec82052fe6bb8212f09daca0/factoryWithTypeCheckers.js#L433

If a boolean prop is passed it is a valid node if it is false, but invalid node if it is true, is it correct or is a bug? It has no sense since is the same type. Could anyone explain this please?

Also if the typeof prop is a function, then it will fall into default switch case (therefore invalid node), but should be a valid node if the function returns a node.

**Comment by ljharb** [comment]
That means false is a node but true is not; sounds right to me.

**Comment by ljharb** [comment]
Also no, a function isn’t a node regardless of what it returns.

**Comment by ljharb** [comment]
false means “nothing”; true means “you have a bug”.

**Comment by ottodevs** [comment]
Understood, thanks.

**Comment by nmifsud-r7** [comment]
I just came across this issue and found this in the docs: 
https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored

> false, null, undefined, and true are valid children. 

This seems to be at odds with the above implementation and explanation?

**Comment by ljharb** [comment]
Interesting, seems like either the docs or the propType is wrong. What happens if you actually render true?

**Comment by nmifsud-r7** [comment]
A little late to reply to this - my apologies. 🙈 

I rustled up an example: https://codesandbox.io/s/jjq6138my9

The output from this in the console is: 
```
Warning: Failed prop type: Invalid prop `children` supplied to `TrueContent`, expected a ReactNode.
    in TrueContent (created by Example)
    in Example
Warning: Failed prop type: The prop `children` is marked as required in `NullContent`, but its value is `null`.
    in NullContent (created by Example)
    in Example
```

So, {null} is a ReactNode but is null and fails the isRequired check, 
{false} is a ReactNode, 
{true} is **not** a ReactNode.

**Comment by ljharb** [comment]
Seems like the react docs need to be updated, then - that's a different repo, so please file an issue/PR there :-)
