### ISSUE TITLE
Not able to install prop-types

### ISSUE THREAD

**Issue by rohyadav** [facebook/prop-types#201]
prop-type is not compatible with node 10 >

<img width="671" alt="prop" src="https://user-images.githubusercontent.com/21152844/43582249-6f299082-9679-11e8-94d7-e0677e41f6e5.png">

**Comment by ljharb** [comment]
That's just yarn. "engines" is purely advisory, and should properly be ignored (like `npm` does).

**Comment by rohyadav** [comment]
I have fixed that so going to close.
thanks @ljharb  for response.
