### ISSUE TITLE
Custom prop-types not working inside shape

### ISSUE THREAD

**Issue by nishant-labs** [facebook/prop-types#202]
Team, 

I was trying to create a custom prop-types for an object using shape as below. Found that prop type for the property inside the shape (`session`) is not working, however same definition for `className` is working fine.

```
Test.propTypes = {
	configs: PropTypes.shape({
		url: PropTypes.string.isRequired,
		scope: PropTypes.string,
		session: (props, propName, componentName) => {
			if (typeof props[propName] === 'function') {
				return new Error(`${propName} must be a function!`);
			}
			return null;
		},
	}).isRequired,
	className: (props, propName, componentName) => {
		if (typeof props[propName] === 'string') {
			return new Error(`${propName} must be a string!`);
		}
		return null;
	},
};
```
I just copied above function to create custom validation.

Am I missing anything or its a bug!!

Thanks
Nishant

**Comment by ljharb** [comment]
Looks right to me; can you share the component code and what’s not working?

**Comment by nishantsinha-5** [comment]
Can't share original code, however I will try to create a jfiddle

**Comment by nishantsinha-5** [comment]
Here is [jfiddle](https://jsfiddle.net/n5u2wwjg/126218/) link with basic example.
I don't know why it's not working for `className` as well.

Thanks.

**Comment by ljharb** [comment]
Your className propType in the fiddle errors only when it *is* a string, so i assume you want `!==` there; i see the same error in the other one.

**Comment by nishantsinha-5** [comment]
@ljharb Thanks for pointing out, Got it why jfiddle was not working for className that was my mistake.
I am new to jfiddle thing.
However my original issue remains same and for 'session' it is still not working.
updated [jfiddle](https://jsfiddle.net/n5u2wwjg/128193/)

**Comment by ljharb** [comment]
Interestingly enough, your fiddle works fine when I use the *non* minified prop-types file.

It seems like the minified version has a bug with shape validations.

**Comment by ljharb** [comment]
Your fiddle works fine when I use the *non* minified prop-types file - this is because the minified one is the production build, which does not actually do anything - you need to use the non-minified one.
