### ISSUE TITLE
Question on prop type validator signature

### ISSUE THREAD

**Issue by mcjazzyfunky** [facebook/prop-types#206]
Just a short question:

What exactly does the fifth argument "propFullName" of React's PropTypes validator functions mean compared to the second argument "propName" and why does React pass null for "propFullName" by default instead of passing the same value as for argument "propName" as default?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/prop-types/index.d.ts#L19

Thanks a lot in advance for the clarification.

**Comment by ljharb** [comment]
propName is the actual property on the props object; full name can be a longer string - for example in a shape, it can be “objectName.propName”. See https://github.com/facebook/prop-types/blob/master/factoryWithTypeCheckers.js#L415

**Comment by mcjazzyfunky** [comment]
@ljharb Aaah, of course ... stupid me :-) .... thank you very much for the clarification.
I'm closing this issue as my question is answered.
