### ISSUE TITLE
Clarification on the usage of imported PropTypes inside arrayOf()

### ISSUE THREAD

**Issue by blacksteed232** [facebook/prop-types#207]
Hi, 

My situation is very similar to [this](https://medium.com/@roman.mahotskyi/hello-many-thanks-for-your-knowledge-sharing-i-was-trying-to-apply-your-approach-to-my-project-d90ee8ef97b4).

I am using prop-types 15.6.2 and I tried to use:

```
import { carPropType } from './car';
...
cars: PropTypes.arrayOf(carPropType);
...
```

where `carPropType` is a PropTypes exported from another file, and I received the warning:

> Warning: Failed prop type: Property `...` of component `...` has invalid PropType notation inside arrayOf.

If I used `cars: PropTypes.arrayOf(PropTypes.shape(carPropType));` then it is fine. I don't understand why this is the case. Strangely enough, if I have `carPropType` defined in the same file where it is used then the warning also does not show up.  

Could you explain to me why this is the case? Thank you!

**Comment by ljharb** [comment]
What's `carPropType`'s code look like? Does it export an object, or an actual propType function?

**Comment by blacksteed232** [comment]
@ljharb It looks like

```
// car.js
...
export const carPropType = PropTypes.shape({
    brand: PropTypes.string.isRequired,
    year: PropTypes.number.isRequired,
})
```

**Comment by ljharb** [comment]
That’s very strange. If you console log the imported shape, what does it look like? What’s its typeof?

**Comment by blacksteed232** [comment]
Hi @ljharb,

So this is the result

```
import { carPropType } from './car.js';

console.log(typeof require('./car.js').carPropType);
// f checkType
console.log(typeof carPropType);
// undefined

console.log(typeof require('./car.js').carPropType);
// function
console.log(typeof carPropType);
// undefined
```

I don't quite get it. I have imported `carPropType` at the top of the file, why is it `undefined`? I can't stumble across this [thread](https://stackoverflow.com/questions/35551366/what-is-the-defined-execution-order-of-es6-imports), and I am using babel as well so should all of my imports are loaded before the `console.log` statement so as to avoid returning `undefined`.

Also, even if that is the case, how does wrapping `carPropType` inside of `PropTypes.shape(carPropType)` makes `arrayOf` works?

**Comment by ljharb** [comment]
@blacksteed232 I think this is something custom to whatever you're transpiling `import` with. What do you get if you `import foo from './car'` and log that? What about `import * as Module from './car'`?

**Comment by blacksteed232** [comment]
@ljharb Ah yes, if I do `import * as Module from './car'` and then use `PropTypes.arrayOf(Module.carPropType)` it works. So it's probably has nothing to do with prop-types, but it seems like its something about JS that I don't understand. I'm relatively new so can you help me understand why this is the case?

**Comment by ljharb** [comment]
@blacksteed232 we should probably close this issue and discuss it elsewhere; it's pretty hard to figure out without a repro repo. If you find me on freenode IRC we can work through it.

**Comment by blacksteed232** [comment]
The problem lies at the import statement, I should have used `import { carPropType } from ...` instead because this is a named export. Wrapping `shape()` around the `undefined` object will suppress the warnings but it's completely wrong.

**Comment by sebastianpatten** [comment]
Mine was resolved when I added an export to my const

**Bad**
`import PropTypes from 'prop-types';

const keyValueShape = PropTypes.shape({
  id: PropTypes.number.isRequired,
  name: PropTypes.string
});

export default keyValueShape;`


**Good**
`import PropTypes from 'prop-types';

export const keyValueShape = PropTypes.shape({
  id: PropTypes.number.isRequired,
  name: PropTypes.string
});

export default keyValueShape;`

**Comment by ljharb** [comment]
@sebastianpatten that's likely because you were doing `import { keyValueShape } from 'path/to/file'` instead of ``import keyValueShape from 'path/to/file'`; it's very much not objectively "good" or "bad" to prefer default, or named, imports.

I'm going to hide both of our comments to ensure people don't get the wrong idea :-)
