### ISSUE TITLE
 How can i constrain func params?

### ISSUE THREAD

**Issue by YouCii** [facebook/prop-types#208]
```
onCheckChange={(isChecked) => this.props.onCheckChange(isChecked)}

SettingItem.propTypes = {
    onCheckChange: PropTypes.func
};
```

It's not enough to constrain the 'onCheckChange' without parms-limit.
Maybe I express my needs clearly.

**Comment by ljharb** [comment]
There's not really a way to do it with JS (without layering a type system on top).

Since propTypes are run on the prop value - which doesn't provide any information about what arguments it's going to eventually be called with - it's basically impossible to check this with propTypes.

**Comment by YouCii** [comment]
emmming,  a little pity.
Thanks for your reply @ljharb
