### ISSUE TITLE
`childrenOfType`?

### ISSUE THREAD

**Issue by ryan-sandy** [facebook/prop-types#209]
How would people feel about a children shorthand?

```
const children = PropTypes.oneOfType([
  PropTypes.arrayOf(PropTypes.node),
  PropTypes.node
])
```

**Comment by ljharb** [comment]
airbnb-prop-types has childrenOf, which is a bit more useful than just “node” imo.

**Comment by ryan-sandy** [comment]
@ljharb That's a nifty package. I didn't know it existed. Thanks for the tip. I think this will solve my problems.

**Comment by oleblaesing** [comment]
Is something like `childrenOfType` also planned for `prop-types`? It's quite useful, to guarantee the correct use of compound components. 😄

**Comment by ljharb** [comment]
Closing as a duplicate of #61.
