### ISSUE TITLE
'array' is forbidden

### ISSUE THREAD

**Issue by z784324922** [facebook/prop-types#212]
![image](https://user-images.githubusercontent.com/31068244/45281865-b8882d00-b50b-11e8-8783-b7e36b4067d1.png)

**Comment by z784324922** [comment]
![image](https://user-images.githubusercontent.com/31068244/45281808-9393ba00-b50b-11e8-8c17-2d6125060da7.png)

**Comment by ljharb** [comment]
This is a lint rule, in eslint-plugin-react (and the airbnb config) and is utterly unrelated to this repo.

Specifically, the lint rule wants you to use `arrayOf` instead of just `array`.

**Comment by z784324922** [comment]
My array is [123,'str'],how to use arrayOf?

**Comment by ljharb** [comment]
`PropTypes.arrayOf(PropTypes.oneOf([PropTypes.number, PropTypes.string]))`

**Comment by z784324922** [comment]
But my array might be [123, 'str'], ['str', 123],  ['str',123,123,'str'] ,I just want to judge the value is a number or string

**Comment by Swivelgames** [comment]
Since this is not an issue with `react/prop-types`, should this issue be closed?

**Comment by ljharb** [comment]
Yes.

**Comment by furevor** [comment]
I have the same problem after updating all packages, including eslint rules etc. I have problems with masked input (https://github.com/text-mask/text-mask/blob/master/componentDocumentation.md#readme)

Here says, that mask it's an array of functions, but I see warning in console "Warning: Failed prop type: Invalid prop `mask[1]` supplied to `renderField`." with this proptype for mask -> 
'mask: PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.func, PropTypes.string]))'

**Comment by ljharb** [comment]
@furevor that’s not really related to this issue; but I’d be willing to bet that the second item in that array isn't a function or a string.

**Comment by furevor** [comment]
> @furevor that’s not really related to this issue; but I’d be willing to bet that the second item in that array isn't a function or a string.

yes, the second element is regexp, but we haven't got regexp in propstype, so the way here is to use propstype.any, of any custom extended-propstype, I suppose, sorry for the wrong messages at this topic

**Comment by ljharb** [comment]
Or instanceOf, but yes.

**Comment by LukaGiorgadze** [comment]
Or you can use shape of Object or Array:
``PropTypes.shape([])``
or
``PropTypes.shape({})``

**Comment by ljharb** [comment]
@LukaGiorgadze shape only takes an object literal, not an array, and if you pass it something with no own properties you’ve defeated the purpose of using a shape at all.
