### ISSUE TITLE
PropTypes.shape false positive when one of the properties of the shape is not required

### ISSUE THREAD

**Issue by yurigenin** [facebook/prop-types#213]
I have the following property definition:

```
value: PropTypes.shape({
      iconMapIndex: PropTypes.number,
      iconType: PropTypes.string
})
```

Neither iconMapIndex nor iconType are required. But when I supply this shape as a value:

```
{
     iconMapIndex: 1
}
```

the validation fails with a message that the value is not valid. On inspection in the debugger I see that it does not like that the iconType is not assigned. But the iconType is not a required property so it should not bark in this case. I see that there is another type PropTypes.exact that I would think could bark in that case but not the PropTypes.shape.

**Comment by ljharb** [comment]
Can you provide a JSfiddle that reproduces this?

**Comment by yurigenin** [comment]
Sorry, jumped the gun. My mistake.
