### ISSUE TITLE
@types/prop-types & @types/react has circular dependency

### ISSUE THREAD

**Issue by adisbladis** [facebook/prop-types#215]
Circular dependencies are a huge issue when working with third party tooling (graphing dependencies, integrating into other build systems etc).

I think the correct solution here would be to put `@types/react` in the `bundleDependencies` (https://docs.npmjs.com/files/package.json#bundleddependencies) attribute in package.json to make the circular dependency invisible to consumers of this package.

**Comment by ljharb** [comment]
Neither of those packages are part of this repo, nor dependencies in it. You'll need to file this kind of issue in DefinitelyTyped.

**Comment by adisbladis** [comment]
Sorry for the confusion
