### ISSUE TITLE
undefined is not an object (evaluating '_react2.PropTypes.string')

### ISSUE THREAD

**Issue by SatishMavani** [facebook/prop-types#218]
below is the code used at one of the place in my app.

import PropTypes from 'prop-types';

BottomNavigationBar.propTypes = {
  outerContainerStyle: ViewPropTypes.style,
  innerContainerStyle: ViewPropTypes.style,
  tabHomeBtn: PropTypes.any,
  tabOneBtn: PropTypes.any,
  tabTwoBtn: PropTypes.any,
  tabThreeBtn: PropTypes.any,
  tabFourBtn: PropTypes.any,
};

I have no idea, How to fix it.

<img width="450" alt="screen shot 2018-09-17 at 10 49 52 pm" src="https://user-images.githubusercontent.com/16286115/45638912-34feab00-bacc-11e8-8332-0f36f6fbabe9.png">

package.jason file is:

<img width="428" alt="screen shot 2018-09-17 at 10 52 14 pm" src="https://user-images.githubusercontent.com/16286115/45638999-71caa200-bacc-11e8-8bc9-0aff74dd814b.png">

**Comment by ljharb** [comment]
Looks like something in your graph is using `React.PropTypes.string`.

**Comment by SatishMavani** [comment]
One of the packages was using PropTypes.string which I was not able to find out. I confirm that in index.android.bundle file that one of the packages still use PropTypes.string. I ended up by upgrading react-native version to 0.54.1 and it started working. Sorry for the late comment :-|
