### ISSUE TITLE
How to use PropsType.shape in oneOf

### ISSUE THREAD

**Issue by philong6297** [facebook/prop-types#219]
I have a `status` prop which can only be `"close"`  or any object that have specific properties like `{position, word}`.
I have tried with this but fail:
![capture](https://user-images.githubusercontent.com/29605147/45837675-07b73480-bd3a-11e8-895f-1aada72c4e0c.PNG)
So how can i define this in PropTypes ?

**Comment by ljharb** [comment]
```js
PropTypes.oneOfType([
  PropTypes.oneOf(['close']),
  PropTypes.shape({…}),
])
``
