### ISSUE TITLE
No warnings for invalid validators inside shape

### ISSUE THREAD

**Issue by asbjornh** [facebook/prop-types#220]
This could be related to #181 

In a project we noticed that having typos in prop type definitions that are nested inside a `PropTypes.shape` do not generate warnings in version `15.6.2`:

```js
{
  a: PropTypes.shape({
    b: PropTypes.boolean // <- is undefined
  })
}
```

I've boiled it down to these test cases:

Case 1:
```js
const PropTypes = require('prop-types');

PropTypes.checkPropTypes({ a: undefined }, { a: "hello" });
```

Case 2:
```js
const PropTypes = require('prop-types');

PropTypes.checkPropTypes(
  { a: PropTypes.shape({ b: undefined }) },
  { a: { b: "hello" } }
);
```

Case 1 generates a warning, as expected:

```
Warning: Failed undefined type: React class: undefined type `a` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
```

Case 2, however, does not output any error or warning 😞 In other words, it seems like if you use an invalid validator inside a `PropTypes.shape`, validation will always pass and no compile time warning or error is visible, which means there might be potential for some sneaky runtime bugs.

I've tested this in many different versions (as low as `0.2.0` and `0.1.0` and it seems to be consistent across all versions.

Is this somehow the intended behaviour? If so, what is a good way to get compile-time errors/warnings for invalid validators used inside `PropTypes.shape`?

**Comment by asbjornh** [comment]
I didn't know about that rule, but it certainly solves my specific symptom (although not the problem).
Adding this to my code right away! 😄 Thanks!

**Comment by ljharb** [comment]
You might be using the minified version, which is for production - use the unminified version.
