### ISSUE TITLE
Invalid prop of type `Map` supplied to Page, expected instance of `Map`.

### ISSUE THREAD

**Issue by Schwartz10** [facebook/prop-types#221]
The title pretty much says it all, I'm building a next.js application using Immutable.js, and for some reason, navigating to pages inconsistently throw this error when it shouldnt. I'm running `prop-types` version `^15.6.2`. It seems to only throw this error with Immutable.js data types, when the app rebundles

**Comment by ljharb** [comment]
This is due to hot module reloading; there's nothing this library can do about it.

**Comment by Schwartz10** [comment]
Thank you for the quick response - do you know why HMR is causing this?

**Comment by ljharb** [comment]
I assume that you have a `PropTypes.instanceOf(Immutable.Map)` or similar somewhere, and that `Immutable.Map` is getting reloaded such that it's a different `===` instance, and so the propType no longer is matching the `instanceof` check.

**Comment by codinronan** [comment]
@Schwartz10 HMR causes this because when HMR'd, React unmounts and remounts components. For props, this makes no difference, but component state is lost, so any props passed as a result of state are also lost.

So if you're storing a Map in a component's state, for example, and passing it into a child component via its props, it will become undefined after HMR.

**Comment by Schwartz10** [comment]
Ahh I see I see, so when the component unmounts, there's a split second before the reload where the props passed to the children are undefined. And then when the error is thrown, the error is thrown, just in time for the component to remount, causing the error message to display in this way? Instead of saying something like "expected undefined to be type Map"? Is that accurate?

**Comment by kurtzur** [comment]
I'm experiencing this problem as well. Coincidentally, I'm also asserting on `Immutable.Map`. However, I'm seeing the problem when running my components in Jest, not webpack. As far as I know, HMR is exclusive to webpack. Any other ideas as to potential causes?

**Comment by kurtzur** [comment]
@ljharb I'm experiencing this problem as well. Coincidentally, I'm also asserting on `Immutable.Map`. However, I'm seeing the problem when running my components in Jest, not webpack. As far as I know, HMR is exclusive to webpack. Any other ideas as to potential causes?

**Comment by kurtzur** [comment]
I believe my problem is an instance of https://github.com/facebook/jest/issues/2549

**Comment by ljharb** [comment]
This is answered.
