### ISSUE TITLE
Ignore thirty part warnings 

### ISSUE THREAD

**Issue by wellyal** [facebook/prop-types#227]
Is there any way that I can ignore (avoid showing up) the third party libraries propTypes warnings?

**Comment by ljharb** [comment]
Why would you want some propType warnings but not others? This package’s propTypes aren’t any different from custom propTypes.

**Comment by wellyal** [comment]
I just don't mind the proptypes regarding the third party libraries because I can't fix it on my project context.

**Comment by ljharb** [comment]
Ah, you mean warnings generated in third-party libraries. Presumably those are caused by incorrect props you're passing them - if they're caused by bugs, you'd also presumably want to know about them and file upstream issues.
