### ISSUE TITLE
Prop type for Text styles?

### ISSUE THREAD

**Issue by niftylettuce** [facebook/prop-types#228]
Not sure what to use here for `<Text>` valid prop types - there isn't clear documentation.  Same for `<View>`.

**Comment by niftylettuce** [comment]
Currently receiving the screenshot below console warning for <https://github.com/joinspontaneous/react-native-loading-spinner-overlay> (widely used cross-platform spinner package for React Native projects):

<img width="379" alt="screen shot 2018-10-13 at 8 11 02 pm" src="https://user-images.githubusercontent.com/523141/46911536-519fce80-cf24-11e8-823e-acc3295a39f1.png">

Ref:
- https://github.com/joinspontaneous/react-native-loading-spinner-overlay/blob/master/index.js#L81
- https://github.com/joinspontaneous/react-native-loading-spinner-overlay/blob/master/index.js#L129

To reproduce, clone the repo linked above, `cd example` and `yarn` then `yarn run example` and `react-native run-ios`.

**Comment by ljharb** [comment]
This sounds RN-specific; I’m not sure it belongs in this library (any more than DOM-specific propTypes would).

**Comment by niftylettuce** [comment]
I will file this in the RN repo, thanks @ljharb
