### ISSUE TITLE
Please git tag release SHAs

### ISSUE THREAD

**Issue by ljharb** [facebook/prop-types#23]
Please add a git tag in the format `v1.2.3` on the npm-published sha for that release. Thanks!

**Comment by gaearon** [comment]
Sorry, we were in a big hurry to get fixes out and some basic things aren't yet set up. We'll get to that.

**Comment by ljharb** [comment]
No worries, just making sure it's not overlooked :-)

It'd be great to set up travis-ci as well (altho I'm sure you have fb internal CI set up, most visitors to the repo won't know that)

**Comment by gaearon** [comment]
No, we don't have anything for this repo right now. :-) As I said the release was rushed and we didn't do the regular release-y things yet.

**Comment by ljharb** [comment]
This has now been taken care of.
