### ISSUE TITLE
Production build each propType is same instance of shim

### ISSUE THREAD

**Issue by AndyOGo** [facebook/prop-types#231]
We use this `propTypes` for custom elements to make runtime parsing based upon prop-types.

Unfortunately in Production the following is true:

```js
import PropTypes from 'prop-types';

PropTypes.string === PropTypes.bool === PropTypes.number === PropTypes.array === PropTypes.object
// -> true
```

Though this should be false.

Currently the `shim` function is static, It would be better to generate it or use a shim factory.
https://github.com/facebook/prop-types/blob/master/factoryWithThrowingShims.js#L15-L59

**Comment by ljharb** [comment]
See #106.

**Comment by AndyOGo** [comment]
Thanks for your immediate feedback.

@gaearon 
@ljharb 
I really hope that you give me a chance to alter your decision and viewpoint about this topic.

If we combine your great approach and this PR we can get both benefits of both worlds - better stripped down production code or dev-only code and if someone like me or others have the crazy idea to use awesome `prop-types` for type casting stuff with custom elememt's attributes or whatever.

I would also argue since you decided to make `prop-types` it's own package, one of it's intention was to see wider utilization, which comes with more use case.

What do you think?

**Comment by AndyOGo** [comment]
@sophiebits 
@gaearon 
I'm sure you have lots of stuff on your todo-list.

I'm really convinced that you do great job. Though I'm sure you allowed yourself a little mistake here and would really insist and appeal to you to correct it. And follow your really nice purity, consistency attitude I know well from other projects of yours.

Hope we can settle this quickly.

**Comment by AndyOGo** [comment]
Just in case anyone else has this issue, you don't need to fork `prop-types`.

```js
import PropTypes from 'prop-types';

// @todo remove as soon as https://github.com/facebook/prop-types/issues/231 is resolved
function getShim(propType) {
  function shim(...args) {
    return propType(...args);
  }

  // make sure to also shim `isRequired`, etc.
  Object.keys(propType).reduce(shimKeys, propType);

  return shim;
}

function shimKeys(propType, key) {
  propType[key] = getShim(propType[key]);

  return propType;
}

const ReactPropTypes = PropTypes;

Object.keys(ReactPropTypes).reduce(shimKeys, ReactPropTypes);

export default ReactPropTypes;
```

**Comment by ljharb** [comment]
Closing per https://github.com/facebook/prop-types/pull/106#issuecomment-398443259, but it's fine to continue discussion if there's anything new.
