### ISSUE TITLE
Please update npm docs prop-types to point to the correct place

### ISSUE THREAD

**Issue by jcollum** [facebook/prop-types#235]
`npm docs prop-types` 

Expected behavior: docs web page is opened 

Actual behavior: https://reactjs.org/ is opened 

If I search for prop-types in that page's search box, I get this page: https://reactjs.org/docs/typechecking-with-proptypes.html#___gatsby 

At the top of the page is this text: 

>React.PropTypes has moved into a different package since React v15.5. Please use the prop-types library instead.

The link there directs you to: `https://www.npmjs.com/package/prop-types` -- **which actually has the docs.**

Please fix it so that `npm docs prop-types` goes to `https://www.npmjs.com/package/prop-types`

**Comment by ljharb** [comment]
It now goes to https://reactjs.org/ .
