### ISSUE TITLE
Better tooling support in vscode

### ISSUE THREAD

**Issue by guledali** [facebook/prop-types#236]
It would be nice if we could get some IntelliSense with prop-types and stuff like auto-completion, type-checking during compile-time. Like getting error reports directly in your editor

**Comment by ljharb** [comment]
Error reports require runtime values; that’s what your tests are for.

**Comment by guledali** [comment]
@ljharb Sorry for the delay

What I meant was something like **tsx** (react and TypeScript), if you don't pass the props the editor will yell at you. I know prop-types is different but I think some improvement can be made to achieve something similar.

Also I know you can configure eslint such as prop-types will complain at you. If you don't pass the correct prop-type. I Want the same experience just without the eslint!

**Comment by ljharb** [comment]
There’s no way to use PropTypes in that manner without a type system, like flow or typescript.

eslint ensures that PropTypes exist - it does not, in any way, validate the actual type of the prop you’re passing against an arbitrary PropTypes (i maintain eslint-plugin-react)

**Comment by ljharb** [comment]
a type system would be what reads the jsdoc. You can’t do that with PropTypes unless all of your values are typed throughout.

**Comment by guledali** [comment]
> a type system would be what reads the jsdoc. You can’t do that with PropTypes unless all of your values are typed throughout.

@ljharb  Okey what would you recommend for vscode user like me that want typechecking similiar to TypeScript/Flow but still wants to use the prop-types library.

**Comment by joshpitzalis** [comment]
vs code picks up JsDoc comments so you can write the following and it will give you type info when you hover over one of the props

```
/** @param {({
 * details:string,
 * dealine: number,
 * goalId: number 
 * })} props */
export const Objective = ({ details, deadline, goalId }) => {...}
```
