### ISSUE TITLE
Identify PropType 

### ISSUE THREAD

**Issue by kamarajuPrathi** [facebook/prop-types#238]
I have a Proptype as mentioned below 

PropTypes.arrayOf(PropTypes.oneOfType([
    TestType1,
  TestType2,
  ]))

where TestType1 and TestType2 are two(objects) Proptypes of shape .

I render based on the object i receive , whether its Type1 or Type2 .

how do i validate whether the object i recieved is of Type1 or Type2 ?

**Comment by ljharb** [comment]
`PropTypes.oneOfType([TestType1, TestType2])` will validate that, assuming both of those are `PropTypes.shape`s. What isn't working?

**Comment by ljharb** [comment]
no.
