### ISSUE TITLE
Mixed arrayOf prop type

### ISSUE THREAD

**Issue by dextermb** [facebook/prop-types#239]
I am currently working on a project where we pass in an array with mixed types. Here's an example:
```js
const dataToPassIn = [
    {},
    [],
];
```

This is an array that contains both arrays and objects. I've attempted to use `oneOfType` and multiple `arrayOf` but still seem to get invalid prop errors. Here's an example:
```js
PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.object),
    PropTypes.arrayOf(PropTypes.array),
])
```

What would be the correct/best way to validate this prop? Both the objects and arrays within the top level array direct children so I don't think `PropType.shape` would work.

Cheers.

**Comment by DivineOmega** [comment]
I believe you can do something similar to the following.

```jsx
myProp: PropTypes.arrayOf(function(propValue, key, componentName, location, propFullName) {
    if (typeof propValue !== 'object' && typeof propValue !== 'array') {
      return new Error(
        'Invalid prop `' + propFullName + '` supplied to `' + componentName + '`. Validation failed.'
      );
    }
  })
```

**Comment by dextermb** [comment]
> I believe you can do something similar to the following.
> 
> ```js-jsx
> myProp: PropTypes.arrayOf(function(propValue, key, componentName, location, propFullName) {
>     if (typeof propValue !== 'object' && typeof propValue !== 'array') {
>       return new Error(
>         'Invalid prop `' + propFullName + '` supplied to `' + componentName + '`. Validation failed.'
>       );
>     }
>   })
> ```

While this is a good solution I'd love to see `PropTypes.arrayOfTypes` implemented or something similar

**Comment by ljharb** [comment]
Your original approach should be inverted:
```js
PropTypes.arrayOf(
  PropTypes.oneOfType([
    PropTypes.arrayOf(arrayItemsPropType),
    PropTypes.shape(objectItemsShape),
  ])
)
```

In other words, it’s always an array - but the array can hold either an array or an object.

**Comment by DivineOmega** [comment]
@ljharb This is far better than my suggestion. I wasn't aware this syntax was supported.

**Comment by alimirakim** [comment]
> Your original approach should be inverted:
> 
> ```js
> PropTypes.arrayOf(
>   PropTypes.oneOfType([
>     PropTypes.arrayOf(arrayItemsPropType),
>     PropTypes.shape(objectItemsShape),
>   ])
> )
> ```
> 
> In other words, it’s always an array - but the array can hold either an array or an object.

Thanks so much, still helping out folks like me years later :) .

**Comment by papuruth** [comment]
How to validate this  const children = [{//react node}, false]
Here the children array can contain both elements as a node
```js
  PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.node, PropTypes.bool])),
```

**Comment by ljharb** [comment]
@papuruth i'm not sure exactly what your pseudocode means; if you want a tuple, of length 2, where the first item is always a node and the second either a node or false, then you can't really do that with this package (your code is the best you can do).

I'd suggest using https://npmjs.com/airbnb-prop-types, which allows you to compose things together to make what you want.

**Comment by papuruth** [comment]
Thanks @ljharb @ctsstc I'll try these

**Comment by godcodevo** [comment]
Thank you!
