### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.string')

### ISSUE THREAD

**Issue by Chinna12345678** [facebook/prop-types#243]
i am seeing this error on android simulator.
i already have the PropTypes imported into the js file , but i am still seeing this error 

undefined is not an object (evaluating '_react.PropTypes.string')
<unknown>
    index.delta?platform=android&dev=true&minify=false:198222:28
loadModuleImplementation
    index.delta?platform=android&dev=true&minify=false:262:14
guardedLoadModule
    index.delta?platform=android&dev=true&minify=false:158:38
metroRequire
    index.delta?platform=android&dev=true&minify=false:88:92
<unknown>
    index.delta?platform=android&dev=true&minify=false:197963:51
loadModuleImplementation
    index.delta?platform=android&dev=true&minify=false:262:14
guardedLoadModule
    index.delta?platform=android&dev=true&minify=false:158:38
metroRequire
    index.delta?platform=android&dev=true&minify=false:88:92
<unknown>
    index.delta?platform=android&dev=true&minify=false:197813:62
loadModuleImplementation
    index.delta?platform=android&dev=true&minify=false:262:14
guardedLoadModule
    index.delta?platform=android&dev=true&minify=false:158:38
metroRequire
    index.delta?platform=android&dev=true&minify=false:88:92

**Comment by ljharb** [comment]
That suggests you're doing `React.PropTypes` somewhere, instead of referencing the imported `prop-types` package.
