### ISSUE TITLE
Use Parent type inside it

### ISSUE THREAD

**Issue by AhmedElywa** [facebook/prop-types#246]
Hello ,

i need to use same parent type inside it like typescript

in typeScript you can say 
`
interface Parent {
title: string,
children: [Parent] | Parent[]
}
`

now to use like this with PropTypes 
`

> const itemType = {
>   title: PropTypes.string.isRequired,
>   replace: PropTypes.bool,
>   prefetch: PropTypes.bool,
>   expanded: PropTypes.bool,
>   group: PropTypes.bool,
>   hidden: PropTypes.bool,
>   home: PropTypes.bool,
>   icon: PropTypes.string,
>   target: PropTypes.string,
>   url: PropTypes.string
> }
> 
> Menu.propTypes = {
>   items: PropTypes.arrayOf(
>     PropTypes.shape({
>       ...itemType,
>       children: PropTypes.arrayOf(
>         PropTypes.shape({
>           ...itemType,
>           children: PropTypes.arrayOf(
>             PropTypes.shape({
>               ...itemType
>             })
>           )
>         })
>       )
>     })
>   )
> }

`
any idea to use it in easy way

thank you

**Comment by ljharb** [comment]
Are you asking about making recursive propTypes?

**Comment by AhmedElywa** [comment]
yes need like this

**Comment by AhmedElywa** [comment]
Thank you this work very good for me 
```javascript
function recursive(...args) {
  return PropTypes.arrayOf(
    PropTypes.shape({
      ...itemType,
      children: recursive
    })
  )(...args);
}
```
