### ISSUE TITLE
the prop-type throw error when i try to update reactV15.2.1 to reactV16.3.0

### ISSUE THREAD

**Issue by tengzj** [facebook/prop-types#250]
when i try to update reactV15.2.1 to reactV16.3.0，the browser show a error which the 'Uncaught TypeError:Cannot read property 'func of undefined' ,but prop-types is installed ,and the gramar is no problem

**Comment by ljharb** [comment]
How are you referencing `PropTypes.func`? `React.PropTypes` no longer exists in React 16.
