### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by YanYuanFE** [facebook/prop-types#254]
SCRIPT1014: 无效字符。
![image](https://user-images.githubusercontent.com/17774285/52543872-06210280-2de8-11e9-99f1-53e7edd5cb65.png)
"prop-types": "^15.7.0",
    "react": "^16.8.1",
    "react-dom": "^16.8.1",

**Comment by YanYuanFE** [comment]
my code repo： https://github.com/YanYuanFE/react-start-app

**Comment by ljharb** [comment]
Can you confirm if it still happens in prop-types 15.6?

**Comment by ljharb** [comment]
Also, what’s the error you get?

**Comment by YanYuanFE** [comment]
> Can you confirm if it still happens in prop-types 15.6?

Yes

**Comment by YanYuanFE** [comment]
> Also, what’s the error you get?

npm start，open IE11

**Comment by YanYuanFE** [comment]
![image](https://user-images.githubusercontent.com/17774285/52544285-e0e1c380-2dea-11e9-94aa-a775a2c9b1ea.png)

**Comment by YanYuanFE** [comment]
![image](https://user-images.githubusercontent.com/17774285/52544307-f951de00-2dea-11e9-98a6-0dc18cd84ecb.png)

**Comment by ljharb** [comment]
Thanks, I think this is the same issue as #255. Fix coming shortly.

**Comment by ljharb** [comment]
v15.7.1 published. Sorry for the inconvenience!

**Comment by YanYuanFE** [comment]
Thanks！
