### ISSUE TITLE
template literal in factoryWithTypeCheckers breaks es5 compatibility

### ISSUE THREAD

**Issue by pfrend** [facebook/prop-types#255]
Problem:
Build issues with webpack when using older uglify-js that can't read es6 input

Version: 15.7

Code:
https://github.com/facebook/prop-types/blob/master/factoryWithTypeCheckers.js#L310

Expected:
Only es5 code exported

Example output of error:
```
ERROR in common.js from UglifyJs
SyntaxError: Unexpected character '`' [./~/prop-types/factoryWithTypeCheckers.js:310,0]
```

Note:
First issue in here - sorry if I'm missing some issue filing rules. Let me know if you need more info.
Thanks!

**Comment by ljharb** [comment]
Thanks, I’ll have a fix for this published shortly.

**Comment by ljharb** [comment]
v15.7.1 published. Sorry for the inconvenience!

**Comment by pfrend** [comment]
awesome, thanks for the quick response time, much appreciated!
