### ISSUE TITLE
Check if prop is a given <Component/>

### ISSUE THREAD

**Issue by plysik** [facebook/prop-types#257]
Hello, 

how can I make the children prop to accept only specified Component?

```javascript
<Parent>
    <Input/>
</Parent>
```

I want to Parent to accept only Input element (not any element ) as its child.

**Comment by ljharb** [comment]
prop-types doesn’t have this built in; you may want childrenOf from https://npmjs.com/airbnb-prop-types

**Comment by ljharb** [comment]
Duplicate of #209.
