### ISSUE TITLE
Typo in static class property declaration  react/no-typos

### ISSUE THREAD

**Issue by shmatapour** [facebook/prop-types#264]
Hi guys, 
I installed  PropTypes and used it on my project , I encountered with below error : 
![err](https://user-images.githubusercontent.com/32255204/54510505-cdce9000-4962-11e9-81fb-cdceed4ea2b4.png)

Please guide me how to solve it if you know, Thanks.

**Comment by ljharb** [comment]
it's `.propTypes`, not `.PropTypes`. The rule just saved you from a bug.

**Comment by abid102** [comment]
same problem occured to me please help me  but i gave 
.propTypes this only.i new to react 
                                                                                                                            Thanks in Advance

**Comment by ljharb** [comment]
@abid102 please file a new issue.

**Comment by maniranganathan97** [comment]
Please, anyone, suggest the answer because I am also facing the same problem

**Comment by maniranganathan97** [comment]
I found the Answer **propTypes** and not **proptypes**

Happy Coding!!!!!!

**Comment by DanielChuks** [comment]
I had the same issue, the bug is from the naming convention. `.propTypes` not `.PropTypes`. Thank You ljharb.

**Comment by juanudk** [comment]
Thank you ljharb.

**Comment by thobishi** [comment]
Thanks, This also worked for me.

**Comment by yogesh1008** [comment]
i am facing same issue , as above mention , resolved my problem

**Comment by yogesh1008** [comment]
Thanks, This also worked for me.

**Comment by krishnadevz** [comment]
```js
import propTypes from 'prop-types';
```
**and use propTypes as @ljharb said it worked ❤🐱‍💻**

**Comment by classyeze** [comment]
thanks it worked..

**Comment by jorgearimitsu** [comment]
> ```js
> import propTypes from 'prop-types';
> ```
> 
> **and use propTypes as @ljharb said it worked ❤🐱‍💻**

Actually you can follow the docs. 

```js
import PropTypes from 'prop-types';
```

and then

```js
Component.propTypes = {
  myProp: PropTypes.array.isRequired
}
```

It's Component.**propTypes** not Component.**PropTypes**

Yes... I know... 🙄

**Comment by omfuke** [comment]
.propTypes work for me instead of .PropTypes

**Comment by virtuousved** [comment]
keep `import` as 
``` import PropTypes from 'prop-types';```

and then to add a property to component  use 
```Todos.propTypes = {}```

This has worked for me. See the cases of `proptypes` in both the places

**Comment by gnsalok** [comment]
```
import PropTypes from 'prop-types';

Todos.propTypes = {
// your code
};

```

**Comment by peepsenpai** [comment]
@ljharb whats the difference between .propTypes and .PropTypes ?
i need ans man, can't sleep without knowing

**Comment by ljharb** [comment]
@peepsenpai one starts with a lowercase P and the other starts with a capital P, and only one of them is correct. Get some rest!

**Comment by Krishna-sm** [comment]
![image](https://user-images.githubusercontent.com/105251808/169304531-1f94b48b-ddb0-4b5f-aed7-8201f9f117be.png)
do this Component.propTypes={
props:PropTypes.string};
