### ISSUE TITLE
Invalid argument supplied to oneOfType

### ISSUE THREAD

**Issue by NemanjaManot** [facebook/prop-types#265]
I am using Jest, and i got this warning when i am running my tests:

*console.error node_modules/prop-types/factoryWithTypeCheckers.js:23
      Warning: Invalid argument supplied to oneOfType. Expected an array of check functions, but received undefined at index 2.*

**Versions:**

```
"react": "^16.8.4",
"react-native": "^0.59.1",
"jest": "^23.6.0",
"babel-jest": "^23.4.2",
"prop-types": "^15.7.2",
```

Does anyone know that is a problem?

**Comment by ljharb** [comment]
Looking at that error message, it looks like you’re providing an array to oneOfType whose third item is undefined. Can you share the code that creates that propType?

**Comment by NemanjaManot** [comment]
For example:

```
        children: PropTypes.oneOfType([
            PropTypes.arrayOf(PropTypes.node),
            PropTypes.node
        ]).isRequired
```
```
        datePickerValue: PropTypes.oneOfType([
            PropTypes.object,
            PropTypes.number,
            PropTypes.string
        ]),
```

**Comment by ljharb** [comment]
Both of those look correct; are you sure those are the lines that are erroring?

**Comment by NemanjaManot** [comment]
I found the error - spelling!
@ljharb thank you, you helped me
