### ISSUE TITLE
Releases, changelogs, and/or tags for major, minor, and patches

### ISSUE THREAD

**Issue by JayAndCatchFire** [facebook/prop-types#27]
There are currently no releases (on github), changelogs, or tags for any versions of this library.  I'd ideally like to see them for all major, minor, and patch versions released to npm so I can see what changed.

**Comment by gaearon** [comment]
Sorry. We prioritised getting bug fixes out over writing release notes this week. We'll get this in order soon.

**Comment by alexilyaev** [comment]
@gaearon I think the [CHANGELOG.md](https://github.com/facebook/prop-types/blob/master/CHANGELOG.md) is fine for now for the release notes, but tagging is a simple way to show up on Releases without much effort.

You can add one line before publishing to npm, based on:
https://docs.npmjs.com/cli/version

**Comment by gaearon** [comment]
We'll be tagging future releases.
