### ISSUE TITLE
Expose PropTypes API for manual use in production code

### ISSUE THREAD

**Issue by vitalif** [facebook/prop-types#270]
Hi, PropTypes is actually a very compact and convenient type checker, so it could be useful to use it in production code, for example, to validate user input. But currently it contains checks explicitly preventing it from being used like that. Could you please remove these checks or make a separate build/library for that?

**Comment by ljharb** [comment]
Seems related to #34.

You can use the development build in production; see the docs added in #262, also in the readme.
