### ISSUE TITLE
memo instance not recognized as PropTypes.func

### ISSUE THREAD

**Issue by ashercoren** [facebook/prop-types#275]
Consider the following propTypes decoration: 

```js
MyComponent.propTypes = {
    element: PropTypes.func,
}
```

Providing a simple React function (`element={(props) => ...}`) works fine, but if I wrap the function with React.memo, I get the following warning:

```
Failed prop type: Invalid prop `element` of type `object` supplied to `MyComponent`, expected `function`.
```

**Comment by ljharb** [comment]
It’s not a function.

If you’re trying to make a propType for “thing you can make an element from”, you may want elementType?

**Comment by ashercoren** [comment]
thanks.
