### ISSUE TITLE
PropTypes.instanceOf(class): right hand side is not an object

### ISSUE THREAD

**Issue by goldmont** [facebook/prop-types#278]
React: 16.8.3
React Native: 0.59.9
PropTypes: 15.7.2

Hi,

I'm not able to restrict prop's type to be a specified instance of a class. By setting 
`something: PropTypes.instanceOf(class)`, the following message appears on the screen:

> Warning: Failed prop type: Right hand side of instanceof is not an object

**Child component**
```javascript
export default class Child extends React.Component {}

Child.propTypes = {
    parent: PropTypes.instanceOf(Parent)
};

Child.defaultProps = {
    parent: null
};
```

**Parent component**
```javascript
export default class Parent extends React.Component {
    render(): * {
        return (
            <Child parent={this} />
        );
    }
}
```

Is there any solution?

**Comment by ljharb** [comment]
The implication is that you didn’t properly import Parent into the Child file - if you console.log it, what’s its value?

**Comment by jzombie** [comment]
I can confirm this doesn't work if checking an arbitrary JavaScript class (not a React component).

Checking with using PropTypes.instaceof(Class) results in the right-hand side is not an object error.

Checking with (classInstance instanceof Class) works as anticipated.

**Comment by ljharb** [comment]
Closing, but happy to reopen with repro info.

**Comment by jzombie** [comment]
I was mistaken when I submitted.  Works as expected.
