### ISSUE TITLE
[Help wanted] How to check prop-types spelling?

### ISSUE THREAD

**Issue by 1483523635** [facebook/prop-types#282]
Details:
I have one react component some like this
```
class SomeComponent extends React.Component {
   render() {
     return <div>
       {this.props.name}
     </div>
   }
}
SomeComponent.PropTypes = {
  name: PropTypes.oneOfType([PropTypes.element, PropTypes.string]),
}
```
This is correct. 

**case 1**:
 but some of the Team members missing write `PropTypes`. 

It's ok, Eslint will tell him.
**case 2**:
some of the Team members will be writing like this 
```
SomeComponent.PropTypes = {
  name: PropTypes.oneOfType(PropTypes.element, PropTypes.string), 
 // missing **oneOfType** needed array
}
```
**case 3**:
 some of the Team Members will be writing like this 
```
SomeComponent.PropTypes = {
  name:  PropTypes.Hahaha
}
```
But for Case 2 and 3, Eslint will not tell me this is error and `Proptypes` not tell me the error in my IDE(such as WebStorm). so how to avoid this?

**Comment by ljharb** [comment]
you’ll get a runtime error; the best practice imo is to make console warnings/errors fail your tests, and then your component’s tests should catch these.

**Comment by 1483523635** [comment]
Yes, a runtime error will always be ignored, because it does not affect the correct behaver. So the only way is to write a test to cover this. It's correct?

**Comment by ljharb** [comment]
Yes.

**Comment by 1483523635** [comment]
Thanks  a lot
