### ISSUE TITLE
Warning: Invalid argument supplied to oneOfType, expected an instance of array.

### ISSUE THREAD

**Issue by devTomek** [facebook/prop-types#287]
```
console.error node_modules/prop-types/factoryWithTypeCheckers.js:23
    Warning: Invalid argument supplied to oneOfType, expected an instance of array.
```

```
EnumCell.propTypes = {
    options: PropTypes.arrayOf(
        PropTypes.shape({
            value: PropTypes.string,
            label: PropTypes.string
        })
    ),
};

EnumCell.defaultProps = {
    options: [],
};
```

```
it("should render select with given options", () => {
        props = {
            ...props,
            options: [
                { value: "test1", label: "test1" },
                { value: "test2", label: "test2" },
                { value: "test3", label: "test3" },
            ]
        };

        wrapper.setProps(props);

        const options = wrapper.find("EnumCell").props().options;

        expect(options).toEqual(props.options);
});
```

Is this package error or my fault?

**Comment by ljharb** [comment]
Are you sure that `EnumCell` is where the error is coming from? You're not using `PropTypes.oneOfType` anywhere in that code.

It seems like it's coming from `wrapper`, not from `EnumCell`.

**Comment by devTomek** [comment]
Sorry fo late response, I have this error only in tests. In developing console and browser console it is fine. But I will check it again.

**Comment by devTomek** [comment]
I checked. I pass everywhere an array. I repeat, this warning appears only in terminal run with jest.

**Comment by ljharb** [comment]
It's probably https://github.com/facebook/jest/issues/2549 - a bug in jest.

**Comment by devTomek** [comment]
Maybe. I can't reproduce it in code sandbox, so I close this topic in hope it will be fixed in other. Thanks for your time :)

**Comment by ambujThalesOW** [comment]
Did anyone find any solution to fix it?

**Comment by ljharb** [comment]
@ambujThalesOW not without a repro repo, unfortunately.
