### ISSUE TITLE
Type error while using prop-types with typescript generics

### ISSUE THREAD

**Issue by BlueSky1997AL** [facebook/prop-types#297]
### Description

In the following codes:

```ts
import PropTypes from 'prop-types';
import React from 'react';

export interface TestProps<T> {
    value?: T;
    onChange?: (param1: string, param2: number, param3: boolean) => void;
}

class Test<T> extends React.Component<TestProps<T>> {
    public static propTypes = {
        onChange: PropTypes.func
    };
}

const el: JSX.Element = <Test onChange={(p1, p2, p3) => console.log(p1, p2, p3)} />;

export default Test;
```

The `onChange` attribute of `Test` component should be in `((param1: string, param2: number, param3: boolean) => void) | undefined` type like this:

![image](https://user-images.githubusercontent.com/28924863/67940585-f152fc00-fc0e-11e9-9448-d754e3d9fa21.png)

But when I pass a function into this attribute, I get a type error: `Parameter 'p1' implicitly has an 'any' type. ts(7006)`

![image](https://user-images.githubusercontent.com/28924863/67944136-bce33e00-fc16-11e9-804d-c0d13e3aad74.png)

When I modify `value?: T;` to `value?: T[];`, it works as expected:

![image](https://user-images.githubusercontent.com/28924863/67945162-33813b00-fc19-11e9-842a-dda68c8cc03f.png)

Remove `propTypes` also works:

![image](https://user-images.githubusercontent.com/28924863/67944998-de452980-fc18-11e9-983f-78ce72e342eb.png)

Remove generics also works:

![image](https://user-images.githubusercontent.com/28924863/67961905-53275c00-fc37-11e9-9b59-0dad12bc3c90.png)

Is this a problem with `prop-types`?

### Environment

- `typescript@3.5.3`
- `react@16.9.0`
- `prop-types@15.7.2`

**Comment by ljharb** [comment]
This repo has no types; perhaps you mean to file an issue on DefinitelyTyped?

**Comment by BlueSky1997AL** [comment]
Opps, I didn't notice that, sorry. I will file an issue on DefinitelyTyped, thanks a lot.
