### ISSUE TITLE
Typo in `PropTypes.checkPropTypes` section of Docs

### ISSUE THREAD

**Issue by marksmccann** [facebook/prop-types#299]
I believe there is a small typo in the `PropTypes.checkPropTypes` section of your `README.md`. Not a big deal, but wanted to point it out. It tripped me up for a little bit and wanted save the next person some time :).

It reads:
```js
PropTypes.checkPropTypes(myPropTypes, props, 'age', 'MyComponent');
```

When I believe it should read:
```js
PropTypes.checkPropTypes(myPropTypes, props, 'prop', 'MyComponent');
```

**Comment by ljharb** [comment]
No, “age” is correct - it matches the code above it in the same section.

**Comment by marksmccann** [comment]
Fair enough, I am sure you no better than I, but are you sure? In the source, that argument is labeled as the `location`, it doesn't seem like it should be the name of a prop.

```js
/**
 * Assert that the values match with the type specs.
 * Error messages are memorized and will only be shown once.
 *
 * @param {object} typeSpecs Map of name to a ReactPropType
 * @param {object} values Runtime values that need to be type-checked
 * @param {string} location e.g. "prop", "context", "child context"
 * @param {string} componentName Name of the component for error messages.
 * @param {?Function} getStack Returns the component stack.
 * @private
 */
function checkPropTypes(typeSpecs, values, location, componentName, getStack) {
    ...
    var err = Error((componentName || 'React class') + ': ' + location + ' type `' + typeSpecName + '` is invalid; ' ...);
```

I believe, if you ran your example it would produce this:

```
Warning: Failed age type: Invalid age `age` of type `string` supplied to
```

instead of this:

```
Warning: Failed prop type: Invalid prop `age` of type `string` supplied to
```

**Comment by ljharb** [comment]
ahh, I see what you mean :-D and also why the mistake was made in #248 - which should be reverted.

**Comment by marksmccann** [comment]
I see you have a `help wanted` tag on the issue, if possible, I would love to make the update and create the PR for you.

**Comment by ljharb** [comment]
That’d be great; that’s indeed what the label means.
