### ISSUE TITLE
React-native: Failed validations not throwing proper console error (red screen)

### ISSUE THREAD

**Issue by zgordon01** [facebook/prop-types#301]
In react-native it appears that all failed validations (`PropTypes.exact`, `PropTypes.objectOf(func)`, etc) all throw errors only in the console. My use case would greatly benefit from `console.error` as if I called it directly, which shows a red screen. I see that in the debugger an error is logged, but it is not showing the red screen.

I guess I could console.error inside of the validator, but that feels like a bit of a hack and not a great solution. Is this a valid solution?

Thanks,

**Comment by ljharb** [comment]
`console.error` is used directly; it seems like perhaps the RNP is replacing `console.error` calls in your code, but not in this package's code?

Either way, there's nothing that can be done about it here, I suspect.

**Comment by zgordon01** [comment]
It's likely that react native adds its own custom implementation of `console.error`. If this package calls something like `window.console.error` it might not work.
When I have time I'll look into this and update this thread when I find more details.

**Comment by ljharb** [comment]
It calls the global console.error.

Closing for now; happy to reopen if there’s something actionable here.
