### ISSUE TITLE
Getting warnings for passing a component to another component as "children"

### ISSUE THREAD

**Issue by scottc11** [facebook/prop-types#303]
I can't figure out how to get rid of this warning, and it is starting to irritate me 🤦‍♂️ahah. Can someone help? Is this a bug or am I doing something wrong?

I am simply passing one component to another component so it can wrap it with some boilerplate stuff, like so:

```
const Wrapper = (props) => {
  return (
    <div>
       {props.children}
    </div>
  )
}

const App = (props) => {
  return (
    <Wrapper>
      <SomeOtherComponent />
    </Wrapper>
}
```

See, this looks fine to me. It looks as all the examples online look. BUT, I still get the following warning.

```
Failed prop type: Invalid prop `children` of type `object` supplied to `Wrapper`, expected `function`
```

I am using `prop-types@15.7.2` and `react@16.8.6`

**Comment by ljharb** [comment]
It can't be that simple; the error message strongly implies that `Wrapper.propTypes` is set to:
```js
{
  children: PropTypes.function
}
```

Are you *sure* that's the *exact, unmodified code* that's producing that error?

**Comment by scottc11** [comment]
turns out you are spot on 😔. I must have set this wrong ages ago and forgot about it. Sorry about that and thanks for your help.
