### ISSUE TITLE
my project can't run prop-types，there's no reaction.

### ISSUE THREAD

**Issue by linyanyuan** [facebook/prop-types#311]
father component:
![image](https://user-images.githubusercontent.com/23653800/73943886-8c552380-492c-11ea-9252-9e90ac64ca84.png)
son component:
![image](https://user-images.githubusercontent.com/23653800/73943944-a858c500-492c-11ea-9d46-740868a17a21.png)
there's no warning
![image](https://user-images.githubusercontent.com/23653800/73944028-cf16fb80-492c-11ea-8034-1095177458d5.png)

**Comment by ljharb** [comment]
I'm a bit confused; `PieChart` renders a `PieCharts`?

**Comment by linyanyuan** [comment]
> 我有点困惑；`PieChart`呈现一个`PieCharts`？

up there's A.js renders a PieCharts,not PieCharts renders a PieCharts.

**Comment by linyanyuan** [comment]
> I'm a bit confused; `PieChart` renders a `PieCharts`?

up there's A.js renders a PieCharts,not PieCharts renders a PieCharts

**Comment by ljharb** [comment]
ok, but you haven't shown me an example of `PieCharts` being rendered without a `title`.

Perhaps you could make a repro repo, so I can see it directly? Screenshots of text are hard to work with.

**Comment by linyanyuan** [comment]
> ok, but you haven't shown me an example of `PieCharts` being rendered without a `title`.
> 
> Perhaps you could make a repro repo, so I can see it directly? Screenshots of text are hard to work with.

I found the problem, because the CDN I used was introduced externally, so it did not take effect. Thank you
