### ISSUE TITLE
Why is this package recommended to be a dependency instead of devDependency?

### ISSUE THREAD

**Issue by TheWirv** [facebook/prop-types#312]
As the title says, is there any particular reason not to make `prop-types` a devDependency?

**Comment by ljharb** [comment]
Because it runs in your production code, even if React compiles out its propTypes *checking* in production. If you don't include `prop-types` in your app, `PropTypes.oneOf()` will throw an error, for example.

Dev deps are for things needed to *develop* a package, like babel/eslint/etc; regular deps are for things needed in/by your code, which includes propTypes.

**Comment by TheWirv** [comment]
> Because it runs in your production code, even if React compiles out its propTypes _checking_ in production. If you don't include `prop-types` in your app, `PropTypes.oneOf()` will throw an error, for example.
> 
> Dev deps are for things needed to _develop_ a package, like babel/eslint/etc; regular deps are for things needed in/by your code, which includes propTypes.

Okay, thanks for the answer. The second part of that was already clear to me, but after having read the following, "... will check props passed to your components against those definitions, and warn _in development_ if they don’t match," I didn't really expect it to run in production code.

**Comment by ljharb** [comment]
Fair enough :-) it's confusing because React doesn't warn on propTypes in production, but the propTypes themselves are still used.

**Comment by TheWirv** [comment]
> Fair enough :-) it's confusing because React doesn't warn on propTypes in production, but the propTypes themselves are still used.

That makes sense :)

**Comment by joetidee** [comment]
Is three a way to keep prop-types enabled in production? I want to observe and report on prop-typ warnings against production data.

**Comment by ljharb** [comment]
I think you’d have to use the development build of react, with NODE_ENV not set to production.

**Comment by joetidee** [comment]
Would be great to make it a feature of the package, defaulting to production.

**Comment by ljharb** [comment]
That’s not within the power of this package - it’s defined within react itself.

**Comment by joetidee** [comment]
So, if the checking of the `production` value here was made optional, this still wouldn't expose prop-type warnings in production?
https://github.com/facebook/prop-types/blob/b67bbd40b5bf8b27475801ecdb7617071ceaccac/index.js

**Comment by ljharb** [comment]
Yes, because React itself calls propTypes on components.

**Comment by joetidee** [comment]
Are you saying that react will not call propTypes in production?

```
Some.Component.propTypes = {
  foo: Proptypes.string.isRequired,
};
```

**Comment by ljharb** [comment]
Yes, that is precisely what I am saying.
