### ISSUE TITLE
Trouble chaining oneOf() with isRequired

### ISSUE THREAD

**Issue by stefcameron** [facebook/prop-types#313]
It appears that there's a chaining issue with `PropTypes.oneOf([...]).isRequired`, which results in `undefined`, even though `isRequired` should be chainable with that type, based on my (very limited) understanding of the code here: https://github.com/facebook/prop-types/blob/master/factoryWithTypeCheckers.js#L341

When I define
```javascript
Component.propTypes = {
  myProp: PropTypes.oneOf([1, 2, 3]).isRequired
};
```
I get this error in the browser console:
```
checkPropTypes.js?c42a:20 Warning: Failed prop type: Component: prop type `myProp` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
```

I'm seeing this in prop-types@15.7.2

Is `isRequired` really not chainable in this case?

**Comment by ljharb** [comment]
It surely should be chainable, and as you can see, [it is](https://runkit.com/ljharb/5e6149ff0f1f9e001af37c65). Are you certain you haven't mocked out `prop-types` somehow?
