### ISSUE TITLE
Cannot represent spread ...props passed to a child

### ISSUE THREAD

**Issue by jamesarosen** [facebook/prop-types#319]
Let's say there's a third-party library like this:
```jsx
export default function Notice({ header, body, className }) {
  return (…)
}

Notice.defaultProps = {
  className: '',
}

Notice.propTypes = {
  header: PropTypes.string.isRequired,
  body: PropTypes.string.isRequired,
  className: PropTypes.string,
}
```

And I want to wrap it:
```jsx
export default function MyNotice({ type, ...props }) {
  return <Notice {{...props, className: `my-notice--${type}`}} />
}

MyNotice.defaultProps = {
  type: 'info',
}

MyNotice.propTypes = {
  type: PropTypes.oneOf([ 'debug', 'info', 'warn', 'error' ]),
}
```

If I don't declare `header`, `body`, and `className` as props on `MyNotice` then I get warnings about unused props.

If I do declare them on `MyNotice`, then I get a warning from [react/no-unknown-property](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/no-unknown-property.md). (I can disable that warning, but it seems like its existence suggests that the team thinks all props should be declared.)

I can try to merge in the child component's prop types:
```jsx
MyNotice.propTypes = {
  ...Notice.propTypes,
  type: PropTypes.oneOf([ 'debug', 'info', 'warn', 'error' ]),
}
```

But that gets a warning from [react/forbid-foreign-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/forbid-foreign-prop-types.md). And even if it didn't, many third-party libraries strip the prop-types from their exported builds.

I'd love to be able to do something like this:
```jsx
MyNotice.propTypes = {
  type: PropTypes.oneOf([ 'debug', 'info', 'warn', 'error' ]),
  ...PropTypes.spread,
}
```

Related: #285

**Comment by ljharb** [comment]
forbid-foreign-prop-types ensures that you use an explicitly exported propTypes shape, and not the `.propTypes` property; any explicitly exported propTypes wouldn't be stripped by any build.

Since you're trying to deal with linter warnings, you should file this on eslint-plugin-react, not here - there's nothing this project can do or needs to do to address your question.

(However, this is also intentional; you *should* be either manually duplicating Notice's propTypes on MyNotice, or, explicitly exporting the propTypes object so you can spread that into MyNotice.propTypes and then disabling the relevant eslint warnings)

**Comment by jamesarosen** [comment]
> you should be either manually duplicating Notice's propTypes on MyNotice

If I do that then I won't get `Notice`'s defaults.

> or, explicitly exporting the propTypes object so you can spread that into MyNotice.propTypes and then disabling the relevant eslint warnings

That assumed I have control over the third-party package. I don't think it's fair to assume that all React packages that use PropTypes export their types as standalone constants.

**Comment by ljharb** [comment]
I agree, but you could make a PR. Either way, these are linter warnings - if they don't make sense for an edge case, use an override comment and explain why you overrode it :-)
