### ISSUE TITLE
`npm install prop-types --save` resolves to tarball

### ISSUE THREAD

**Issue by juanca** [facebook/prop-types#32]
I'm not sure if this is normal for `npm` <sub>-- and I can't find much on google?</sub>

Issuing the following command:
```
> npm install prop-types --save
somePackage /Users/user/some-package
└── prop-types@15.5.8
``` 

resolves in:
```
"prop-types": "https://registry.npmjs.org/prop-types/-/prop-types-15.5.8.tgz",
```

Issuing the following command 
```
> npm install prop-types@latest --save
somePackage /Users/user/some-package
└── prop-types@15.5.8  invalid
``` 

resolves in:
```
"prop-types": "^15.5.8",
```

This is not the case for all other packages. Just wanted to give a heads up in case it's something about the packaging of this module.

**Comment by acbabis** [comment]
I am also experiencing this. I wonder if it's by design...

**Comment by ljharb** [comment]
This is an npm bug; not related to any single package. Upgrade to latest.
