### ISSUE TITLE
Recursively nested PropTypes API?

### ISSUE THREAD

**Issue by drolsen** [facebook/prop-types#320]
I'm all for PropTypes, really helps keep me and my teams code all on the same page and agreed upon..

However, is this of anything to be concerned about?

![image](https://user-images.githubusercontent.com/553928/87001008-41556b80-c16b-11ea-966e-69732e050855.png)

I understand it could just be recursively instances of its self and nothing more.. but figured it couldn't hurt to ask what is going on here?

Using:
**//unpkg.com/react@16.8.0/umd/react.development.js**
**//unpkg.com/prop-types@15.7.2/prop-types.js**

I almost wanna keep clicking to see if it ends..

**Comment by ljharb** [comment]
It's not concerning; circular references are just fine, look at `window.window.window` ad infinitum :-)

Indeed, I see that this is intentionally added in #20.
