### ISSUE TITLE
Remove `process` shim

### ISSUE THREAD

**Issue by mnpenner** [facebook/prop-types#323]
If you look in https://unpkg.com/prop-types@15.7.2/prop-types.js, there's a shim for the `process` var:

```js
// shim for using process in browser
var process = module.exports = {};
```

I'm pretty sure this is causing a conflict with my code. Can you remove the shim or at least change it to check if it's already been set?

**Comment by ljharb** [comment]
Why would it? That variable is being set inside an IIFE, which shouldn't conflict with anything outside of that bundle.

What's the conflict you think it's causing?

**Comment by ljharb** [comment]
https://blog.sindresorhus.com/webpack-5-headache-b6ac24973bf1 may be relevant.

Node module bundlers that don't automatically bundle node builtins whenever possible are broken; if you use one of these, you'll need to fix your bundler config (in webpack 5, you can use ProvidePlugin to unbreak things, for example).

**Comment by mnpenner** [comment]
I see now. I thought it was a global because it wasn't indented. I think you're right, this was probably a webpack 5 issue.
