### ISSUE TITLE
Prop type for Date

### ISSUE THREAD

**Issue by nomanurrehman** [facebook/prop-types#325]
I just noticed there is no type checker for a date. It is also not possible to somehow have a regular expression that could be a fit in solution for this.

Was there any specific design decision that motivated this choice or pull requests are welcome for this?

Thank you for the great work.

**Comment by ljharb** [comment]
You can use `PropTypes.instanceOf(Date)`, or for a more robust solution, use https://www.npmjs.com/package/is-date-object with `predicate` from https://www.npmjs.com/package/airbnb-prop-types.
