### ISSUE TITLE
Why PropType.boolean is function

### ISSUE THREAD

**Issue by tdimdimich** [facebook/prop-types#33]
```javascript: 
Modal.propTypes = {visible: PropTypes.boolean}
```

> Warning: Failed prop type: Modal: prop type `visible` is invalid; it must be a function, usually from React.PropTypes.

I think that the boolean type should be called 'boolean'
You can add boolean as alias for bool, for expected behavior PropTypes

I think if undefined PropType shouldn't be function

**Comment by gouegd** [comment]
`PropTypes.boolean` is undefined. You get a warning because React expects a function.
`PropTypes.bool`, like `PropTypes.string` and others, is a function that validates your props (so it can't be a `boolean`, a `string`, etc).

**Comment by gaearon** [comment]
Yes, it’s expected (you needed `PropTypes.bool` as documented in the README). Perhaps the warning could say `Have you misspelled a PropType?` at the end if the validator is `undefined`. Would either of you be interested in sending a PR to make the warning better?

**Comment by gouegd** [comment]
I can probably have a go at this next week if nobody does before.

**Comment by jonleung** [comment]
👍
