### ISSUE TITLE
Add ability to override `isRequired`

### ISSUE THREAD

**Issue by dkreft** [facebook/prop-types#339]
When passing props from one component to another, I like to have a single source of truth for my propTypes--the component that actually uses the prop:

```jsx
// File: A.jsx

import PropTypes from 'prop-types'

import B from './B'


export default function A({ className, foo }) {
  return (
    <div className={ className }>
      <B foo={ foo } />
    </div>
  )
}

A.propTypes = {
  className: PropTypes.string,
  foo: B.propTypes.foo,
}
```

```jsx
// File: B.jsx

import PropTypes from 'prop-types'


export default function B({ foo }) {
  return ( /* blah blah blah */ )
}

B.propTypes = {
  foo: PropTypes.string.isRequired,
}
```

In this case, the `foo` property on `A` is mandatory...which is great. Well, that is until I want to make `foo` optional on `A` because I'm declaring a default value for it:

```js
A.propTypes = {
  className: PropTypes.string,
  // Warnings ensue...
  foo: B.propTypes.foo,
}

A.defaultProps = {
  foo: 'default value provided by A',
}
```

What I'd like to be able to do is override the `isRequired` flag, perhaps like this:

```js
A.propTypes = {
  className: PropTypes.string,
  foo: B.propTypes.foo.optional,   // <=== `optional` overrides `isRequired`
}
```

If there's some other reasonable way around this problem, I'm all ears.

**Comment by ljharb** [comment]
If `foo` is required for `B`, then it's absolutely required for `A` in your example. In other words, omitting it on A will be a bug when it gets to B and isn't present, so it _should_ be required for both.

Do you have another example?

**Comment by dkreft** [comment]
@ljharb, I think you may have missed `A.defaultProps` in the third code block:

<img width="918" alt="Screen Shot 2021-03-18 at 2 20 21 PM" src="https://user-images.githubusercontent.com/272745/111699252-1db3ec00-87f5-11eb-9bb8-c1f5161ee362.png">

In that case, it is optional for `A` by virtue of the `defaultProps`, but of course, `prop-types` still recognizes it as a mandatory property in `A` because there's no way to override the `isRequired`...which is the issue that I'm seeking to resolve.

**Comment by ljharb** [comment]
I could still pass `foo` as `null` and it would break, because it should, in fact, be required on A.

**Comment by dkreft** [comment]
I feel like maybe we're speaking past each other.

I'm trying to figure out a way to make the param mandatory for `B` but *optional* for `A`, but it sounds like you're talking about the _status quo_.

If you have a recommendation for how to achieve this, I'm all ears.

**Comment by ljharb** [comment]
This is how:
```js
A.propTypes = {
  foo: B.propTypes.foo, // required
};
A.defaultProps = {
  foo: 'some default'
};
```
This way, `foo` is required, but because it is _also_ defaulted, the user doesn't have to pass it - but if they pass `null` it's invalid, which is correct.

**Comment by dkreft** [comment]
Hrmm. Well, then...I suppose I'll just crawl back under the rock out from which I came.

![image](https://user-images.githubusercontent.com/272745/111723504-de9b9000-8820-11eb-86b4-1516bb7f487c.png)
