### ISSUE TITLE
Check Proptypes for a component

### ISSUE THREAD

**Issue by devmota** [facebook/prop-types#341]
Speak up, guys! How are you?

Let me explain what I'm facing:

I have a form builder, which receives which forms should be assembled in the template, however, each of these forms has different propTypes.

In this my builder, I would like to check the forms that were requested for assembly and ensure that it was passed via the builder's property, all the dependencies of the junction of each requested form.

Example:

```
Form1.propTypes = {
name: PropTypes.string.isRequired,
age: PropTypes.number,
}

Form2.propTypes = {
zipcode: PropTypes.number,
address: PropTypes.string.isRequired,
}
```

In this case, the builder would need to receive "name" and "address".

Is there a way today for me to be able to list the proptypes of a component and check exactly what are the required items and the type of content?

Node: 10.x
React: 16.4.1
PropTypes: 15.7.2

**Comment by ljharb** [comment]
You can iterate over the `.propTypes` object on a component, if that's what you mean - because custom propTypes exist, there simply is no reliable way to determine "required" or "type" from the propType function (although for known propTypes there's various ways).
