### ISSUE TITLE
Document defaultProps in README

### ISSUE THREAD

**Issue by scott-ln** [facebook/prop-types#343]
`defaultProps` are not mentioned at all in the README. This is not useful if you've just gotten an error from [`eslint-plugin-react/require-default-props`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md). The top Google hit for "React defaultProps" is [this page on the React site](https://reactjs.org/docs/typechecking-with-proptypes.html) which directs you to look at the `prop-types` documentation instead.

**Comment by ljharb** [comment]
A sentence that points back to https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values seems reasonable.

**Comment by scott-ln** [comment]
Just looked at that page again and I see now that the message at the top which I mentioned is intended for people who were using the old `React.PropTypes`. That wasn't clear to me as a new user encountering an important-looking yellow box at the start of the page, so perhaps the wording there could also be modified.

**Comment by ljharb** [comment]
I have no control over react’s docs; you’d have to file an issue/PR on react itself for that.

**Comment by scott-ln** [comment]
Gotcha, will do - thanks Jordan.

**Comment by ljharb** [comment]
Closing in favor of https://github.com/reactjs/reactjs.org/issues/3632
