### ISSUE TITLE
Is this the correct way to define an array proptype of 2 moment instances?

### ISSUE THREAD

**Issue by Pacheco95** [facebook/prop-types#344]
I need to define a PropType for a date range prop like:

```js
[moment(), moment()]
```

Is this correct? Is there a better way?

```js
DatePricker.propTypes = {
  createdAt: PropTypes.arrayOf(PropTypes.instanceOf(moment)),
};
```

I tested passing an array with two normal javascrip dates and console log this
```Warning: Failed prop type: Invalid prop `coupon.createdAt[0]` of type `Date` supplied to `CouponsFilter`, expected instance of `hooks`.```

Can I replace this error message to ends with `expected instance of 'moment'`?

**Comment by ljharb** [comment]
`hooks` is presumably the name of the `moment` function (`moment.name`?) otherwise i'm not sure where that name would come from.

This package's propTypes don't provide the ability to customize the message; you may want to check out https://npmjs.com/airbnb-prop-types for that.

**Comment by Pacheco95** [comment]
Thank you for your response. I will check it out!
What about this questions? "Is this correct? Is there a better way?". Can you help me with them?

**Comment by ljharb** [comment]
It is correct, and there is no better way using the core prop-types package.
