### ISSUE TITLE
Getting error "undefined is not an object (evaluating '_react.PropTypes.array')"

### ISSUE THREAD

**Issue by kishanbharda** [facebook/prop-types#351]
Hello, 

I am running the react-native project with the following configuration : 
```
"react": "16.8.3",
"react-native": "0.59.8",
```

I have installed `"prop-types": "^15.7.2",`, now when I am running the app I am getting error :
>undefined is not an object (evaluating '_react.PropTypes.array')

Can anyone please tell me why this is happening?

**Comment by ljharb** [comment]
How are you importing this package in your code?

**Comment by kishanbharda** [comment]
An error was on one of the another library that I have installed. That library using the `prop-types` and was using old-type imports. So I changed the import type and it's worked.
