### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNative.TextPropTypes.style')

### ISSUE THREAD

**Issue by utkarshchowdhary** [facebook/prop-types#352]
Referencing TextPropTypes.style for setting Text style prop for a component throws type error.

**Comment by ljharb** [comment]
I'm not sure how this is related to the `prop-types` package.

**Comment by utkarshchowdhary** [comment]
I don't know where the issue lies , i'm using prop-types package for documenting props for a component where i wanna pass styles specific to TEXT Component as a prop but specifying TextPropTypes.style for the style prop inside static propTypes object dosen't work it throws TypeError. It's working for ViewPropTypes.style though.

**Comment by ljharb** [comment]
Right but that’s about react or your own code - TextPropTypes and ViewPeopTypes don’t come from this package,

**Comment by utkarshchowdhary** [comment]
Oh Okay, if so can u demonstrate a working example of how would i pass a style object as a prop specific to TEXT Component and utilize prop-types package to validate that ?

**Comment by ljharb** [comment]
This package exports specific validators. If you’re not using one, this repo isn’t the place to get help, I’m afraid.

**Comment by utkarshchowdhary** [comment]
ah, thanks anyway.
