### ISSUE TITLE
Use of Hard-coded Password

### ISSUE THREAD

**Issue by rajeevdodda** [facebook/prop-types#357]
When we scanned our application using a static scan tool, it reported a security vulnerabity in the below line with a category of "Use of Hard-coded Password"

https://github.com/facebook/prop-types/blob/4de0644a10a554d0a556daa39f029369bc007ea5/lib/ReactPropTypesSecret.js#L10

**Comment by sdoppalapudi** [comment]
> When we scanned our application using a static scan tool(Veracode), it reported a security vulnerabity in the below line with a category of "Use of Hard-coded Password"
> 
> https://github.com/facebook/prop-types/blob/4de0644a10a554d0a556daa39f029369bc007ea5/lib/ReactPropTypesSecret.js#L10

**Comment by ljharb** [comment]
Then your tool is pretty silly - just because a variable has the name “secret” doesn’t mean it’s actually a secret value, and your tool shouldn’t be warning you about third-party code.
