### ISSUE TITLE
Latest version of prop-types is having vulenrability.Any idea that which safer version shall I switch to?

### ISSUE THREAD

**Issue by akanksha2306** [facebook/prop-types#362]
Hi 
I am using the latest version of prop-types but its vulnerable.I was unable to find the information about non vulnerable version of this library.Any details or any idea about which is the safe version should I switch too?

**Comment by ljharb** [comment]
In what way is it vulnerable?

**Comment by ljharb** [comment]
Closing; there's no actual vulnerability I'm aware of.
