### ISSUE TITLE
_propTypes.default.shapeOf is not a function

### ISSUE THREAD

**Issue by ad99526** [facebook/prop-types#374]
![Screenshot Capture - 2022-02-03 - 14-46-41](https://user-images.githubusercontent.com/54868382/152314044-9feea41f-cc02-4ceb-b746-022e28d9a38b.png)

Can't figure out what the problem is
Below is the codesandbox to see the code producing this error
I am using following packages and versions:
    "prop-types": "15.8.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.0"

**Comment by ljharb** [comment]
`shapeOf` has never existed. You want `shape` or `objectOf`.
