### ISSUE TITLE
TypeError: Cannot destructure property 'checkPropTypes' as it is undefined.

### ISSUE THREAD

**Issue by code-masala** [facebook/prop-types#377]
when I am doing testing using jest in svelteKit .
Error:
`TypeError: Cannot destructure property 'checkPropTypes' of 'pkg' as it is undefined.`
<img width="674" alt="Screenshot 2022-03-17 at 1 32 54 PM" src="https://user-images.githubusercontent.com/93755988/158763902-42c7947a-78c6-4108-abc0-d1d7ba1de948.png">

**Comment by code-masala** [comment]
is this related to prop-types or jest?

**Comment by ljharb** [comment]
Certainly not `prop-types` - you can try here https://runkit.com/npm/prop-types

Perhaps you mocked out the module incorrectly?
