### ISSUE TITLE
SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED

### ISSUE THREAD

**Issue by luisgcoss** [facebook/prop-types#389]
Does somebody have notice this?. When you use a spread operator to see what the function in a custom Validator receives the fifth paramather says "SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED"
![image](https://user-images.githubusercontent.com/50281580/198703631-6a64cc61-652f-4435-b8ea-1931d5b67eaf.png)
![image](https://user-images.githubusercontent.com/50281580/198703704-712dbb33-5131-4e9f-b33d-2d5cd251e336.png)
Will I be fired?

**Comment by ljharb** [comment]
Yes, it's been widely shared on the internet:L https://www.reddit.com/r/javascript/comments/3m6wyu/found_this_line_in_the_react_codebase_made_me/ it's quite old news.
