### ISSUE TITLE
The `prop-types` package import is not suddenly recognized when running jest

### ISSUE THREAD

**Issue by dominikj111** [facebook/prop-types#399]
I'm not sure if it is `prop-types` related, but this issue breaking my unit tests.
I have been able to solve this by masking `prop-types` in the `jest.config.js`.
```
moduleNameMapper: {
   "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2||css)$": "<rootDir>/tests/__mocks__/fileMock.js",
   "^\\(Base\\)/(.*)$": "<rootDir>/src/Base/$1",
   "^\\(Utilities\\)/(.*)$": "<rootDir>/src/Utilities/$1",
   "^\\(DataFilter\\)/(.*)$": "<rootDir>/src/DataFilter/$1",
   "prop-types": "<rootDir>/tests/__mocks__/prop-types.js",
},
```
Where my `prop-types.js` looks like this:
```
const PropTypes = {
	arrayOf: () => ({}),
	shape: () => ({}),
	oneOfType: () => ({}),
	oneOf: () => ({}),
	objectOf: () => ({}),
	string: {},
	number: {},
	func: {},
	bool: {},
	object: {},
	element: {},
};

module.exports = PropTypes;
module.exports.default = PropTypes;
```

Is this an issue?
How that happened?

I liked that my properties have been type checked during the testing.

**Comment by ljharb** [comment]
Do you have NODE_ENV set to production, perhaps? If so, that would break most test runs.

That said, I'm not sure why you're mocking it out, nor what "issue" you mean.

**Comment by ljharb** [comment]
Yes, a repro app would be most helpful. Either way, this package hasn't changed in awhile, so it's almost certainly something to do with jest or your jest config.

**Comment by dominikj111** [comment]
I have minimal repository to reproduce this issue [dominikj111/issue-minimal-proptypes-jest](https://github.com/dominikj111/issue-minimal-proptypes-jest)

The `npm test` will fail, but I realized that after rename the component `ControlHeader.tsx` to `ControlHeader.jsx` problem disappear. I don't know why yet.

**Comment by dominikj111** [comment]
So on the end the problem was in the `tsconfig.json` file.

This is what I had:
```
{
  "include": ["src/**/*", "tests/**/*"],
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "nodenext",
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "resolveJsonModule": true,
    "allowJs": true,
    "checkJs": true,
    "lib": ["ESNext", "DOM", "ESNext.String"],
    "jsx": "react",
    "baseUrl": "."
  }
}
```

And I was missing `"esModuleInterop": true,` :)

**Comment by ljharb** [comment]
aha, indeed - without esModuleInterop and allowSyntheticDefaultImports, TS's module system is fundamentally broken.
