### ISSUE TITLE
Using plain "PropTypes.bool" results in "warning.js:36 Warning: Failed prop type:"

### ISSUE THREAD

**Issue by Bezilon** [facebook/prop-types#46]
Here is the snippet that gives me the error:

```
import React, { Component } from 'react'
import PropTypes from 'prop-types'

import SmartField from './SmartField'

export default class MyComponent extends Component {
  static propTypes = {
    title: PropTypes.string,
    parameters: PropTypes.object.isRequired,
    onChange: PropTypes.func.isRequired,
    isStatic: PropTypes.bool,
    hidden: PropTypes.bool
  }

  render() {
    ...
  }
}
```

Makes no sense in my book that this is the only instance in my whole project where PropTypes.bool refuses to work

> Warning: Failed prop type: MyComponent: prop type `isStatic` is invalid; it must be a function, usually from React.PropTypes.

**Comment by ali-l** [comment]
What version of React are you using? The fact that it mentions `React.PropTypes` in the message makes me think that the version being used has the old, built-in prop types, which isn't compatible with the standalone package.

The issue I'm speaking of is described here: https://github.com/facebook/prop-types/blob/master/README.md#what-happens-on-other-react-versions

**Comment by Bezilon** [comment]
My react is v15.5.4 currently so this should not be an issue according to the article you linked. Also I'm not calling validator functions anywhere in my project.

**Comment by ljharb** [comment]
Is this still an issue? Closing until it can be reproduced.
