### ISSUE TITLE
Is there a prop type for stateless functions that return a jsx component?

### ISSUE THREAD

**Issue by tehandyb** [facebook/prop-types#52]
I wanted to use PropTypes.element to validate that the incoming prop was a component, but it is a stateless function that returns a JSX element. My eslint tells me that a function was supplied, but an element was expected. Is this an eslint issue, or should there be a prop type for a React stateless function?

**Comment by alexkrolick** [comment]
Since the render callback is just a function, there's no way in pure Javascript to check the type of the return value. A static type checker like Typescript or Flowtype could do this for you, though.

**Comment by ljharb** [comment]
You may be looking for this feature request: https://github.com/facebook/react/issues/10020

**Comment by ljharb** [comment]
@tehandyb alternatively, if you accept a thunk as a prop, you need to check its return type at runtime, in the render path.

Separately, the SFC function itself is not an element, it's a Component - `<SFC />` is an element. The way I'd validate it is to use it in a jsx/createElement context, and let React handle it.

**Comment by tehandyb** [comment]
@ljharb yeah that's even better than what I was looking for!

**Comment by ljharb** [comment]
This seems answered.
