### ISSUE TITLE
Broken link in comments of index.js

### ISSUE THREAD

**Issue by katsos** [facebook/prop-types#53]
You can find the broken link (400 error) in the links below.

https://github.com/facebook/prop-types/blob/36d7a3331b6b312b7a4ec28085f772603395b6fc/index.js#L23

https://github.com/facebook/prop-types/blob/36d7a3331b6b312b7a4ec28085f772603395b6fc/index.js#L28

**Comment by miguelcg** [comment]
The links work now. Could you please double check? Thanks.

**Comment by katsos** [comment]
@miguelcg indeed.
