### ISSUE TITLE
importing prop-types into a HOC is `undefined`

### ISSUE THREAD

**Issue by mrbinky3000** [facebook/prop-types#62]
I'm creating a higher order component following the example on the [React documentation website](https://facebook.github.io/react/docs/higher-order-components.html#dont-mutate-the-original-component.-use-composition.).

Here's a very simplified version of my HOC.  This is in a file by itself.

``` 
import React from 'react';
import PropTypes from 'prop-types';

export default function HigherOrderComponent(WrappedComponent) {
  class Wrapper extends React.Component {
    static propTypes = {
      children: PropTypes.oneOfType([
        PropTypes.arrayOf(PropTypes.node),
        PropTypes.node,
      ]).isRequired,
    }

    componentDidMount() {
      // this.doStuff()
    }

    render() {
      return (
        <WrappedComponent
          {...this.props}
          wrapped={'Hey, I am a prop from the HOC!'}
        >{this.props.children}</WrappedComponent>);
    }
  }

  return Wrapper;
}
```

For some reason, PropTypes is "undefined".  However, if I change every instance of `PropTypes` to `React.PropTypes`, it works just fine because it is accessing the PropTypes object from React.

It could be something related to babel / rollup, but I'm not sure.  But I am suspicious of the issue being in Babel or Rollup because React gets passed through just fine.

Here is my .babelrc file:

```
{
  "presets": ["es2015-rollup", "react"],
  "plugins": [
    "transform-class-properties"
  ]
}
```

Checklist:
- 'prop-types' is listed in my package.json under "dependencies"
- I deleted my node_modules folder and ran `npm i`
- `import PropTypes from  'prop-types';` in other files seems to work just fine.  I think it has to do with PropTypes being used in a function?

I have a repo with the issue on github if you want to see the full example.  PM me if you want to check that out.

**Comment by dubert** [comment]
Did you resolve this issue?

**Comment by mrbinky3000** [comment]
Yes.  Sorry for the delay in my reply. It was something wrong with my local environment.  I've unfortunately forgotten what was wrong.
