### ISSUE TITLE
Optimize defaultProps with propTypes

### ISSUE THREAD

**Issue by Stupidism** [facebook/prop-types#67]
**Do you want to request a *feature* or report a *bug*?**
feature, 
PropTypes.string('default string');
**What is the current behavior?**
Two statics representing the same thing is kind of Trivial. 
```js
Component.propTypes = {
  foo: T.string,
  bar: T.number.isRequired,
};
Component.defaultProps = {
  foo: '12',
}
```
Sometimes people write useless code with this design. And you can't tell what is the author wanted.
```js
Component.propTypes = {
  foo: T.string,
  bar: T.number.isRequired, // unnecessary isRequired.
};
Component.defaultProps = {
  foo: '12',
  bar: 12, // or unnecessary defaultProp.
}
```
**What is the expected behavior?**
Make defaultProps work with propTypes. One static other than two statics will be much easier for HOC and Developers to customize, modify or remove. 
```
Component.propTypes = {
  foo: T.string('12'),
  bar: T.number.isRequired,
  // or
  foo: T.string.default('12'),
};
```

**Comment by michaelbreyes** [comment]
Personally, I like the style
```
Component.propTypes = {
  foo: T.string.default('12'),
};
```

This kind of change would be helpful when combining PropTypes.shape with PropTypes.arrayOf which is currently not possible.

```
Component.propTypes = {
  items: T.arrayOf(T.shape({ foo: T.string.default('none') })),
};
```

**Comment by ljharb** [comment]
This would have to be a feature in React itself, before this library could support it.

**Comment by igoradamenko** [comment]
I've left this comment just to help other guys like me to find the detailed explanation of the declining this feature:

> This is intentional, as defaultProps is a core part of the API (and is important in production) whereas propTypes give you some development-time validation, and in some cases can be replaced by Flow or TypeScript. We don’t want to conflate these two APIs, even at the expense of some perceived duplication.

https://github.com/facebook/prop-types/issues/37#issuecomment-298948570
