### ISSUE TITLE
Warn for PropTypes that don't exist but do exist with a different case

### ISSUE THREAD

**Issue by aweary** [facebook/prop-types#7]
Original issue: https://github.com/facebook/react/issues/6153

**Comment by katsos** [comment]
Is anyone working on this one? I'd like to contribute.

@aweary can you please provide me the copy to display when the prop-type doesn't exist?

**Comment by lukescott** [comment]
Isn't #11 somewhat related? If you warned about every property that wasn't defined, wouldn't that highlight `onaction` as not defined? You could also look for similar cases though to provide a better error message - "did you mean `onAction`?".

**Comment by ali-l** [comment]
@lukescott A warning about different capitalization would be useful in any scenario, as it is most likely a typo. The issue mentioned in #11 does overlap, but seems like it should be opt-in.

**Comment by ljharb** [comment]
This seems like something that React itself would have to do. Separately, `PropTypes.exact` can catch all these typos by warning on any unrecognized prop.
