### ISSUE TITLE
Import via default or named export?

### ISSUE THREAD

**Issue by johanarnor** [facebook/prop-types#70]
Hi!

I don't really know if this is an issue, or if it is by design, but I'm curious to know why one can import PropTypes both as a default export and as a named export. Both these versions work (using babel):

```import PropTypes from 'prop-types'```
```import {PropTypes} from 'prop-types'```

Is one to prefer over the other (although they export the same object https://github.com/facebook/prop-types/blob/master/factoryWithThrowingShims.js#L56)?

**Comment by brneto** [comment]
I have the same doubt!

**Comment by johanarnor** [comment]
@brneto No, I guess one can just use both.
