### ISSUE TITLE
Despite upgrading to React 0.14.9, "Warning: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package." still shows.

### ISSUE THREAD

**Issue by rzhou186** [facebook/prop-types#72]
I'm running React 0.14.9, as well as another package that uses `prop-types`. Earlier, I was running React 0.14.6 and receiving this warning. Despite upgrading to React 0.14.9, the warning is still showing.

**Comment by ljharb** [comment]
This suggests that something in your dependency graph either isn't using a new enough version of react and react-dom, or that it's calling a propType directly.
