### ISSUE TITLE
Should prop-types remove itself in the production build?

### ISSUE THREAD

**Issue by a-x-** [facebook/prop-types#73]
... and how to reach this behaviour?

**Comment by samuxyz** [comment]
@a-x- have you been using the `transform-react-remove-prop-types` plugin from Babel before Or you are asking for React to do it automatically?

**Comment by a-x-** [comment]
I think about the recommendation for all users to use something like `transform-react-remove-prop-types` by default in the setup manual.

p.s. thank you for reference to `transform-…`, I cannot found it

**Comment by ljharb** [comment]
This seems answered.
