### ISSUE TITLE
Cannot find module "fbjs/lib/emptyFunction"

### ISSUE THREAD

**Issue by divined** [facebook/prop-types#76]
Uncaught Error: Cannot find module "fbjs/lib/emptyFunction"

factoryWithTypeCheckers.js?dcd5:12
------------
./~/prop-types/~/fbjs/lib/emptyFunction.js

Module build failed: Error: ENOENT: no such file or directory, open 'node_modules\prop-types\node_modules\fbjs\lib\emptyFunction.js'

./~/prop-types/~/fbjs/lib/invariant.js

Module build failed: Error: ENOENT: no such file or directory, open 'node_modules\prop-types\node_modules\fbjs\lib\invariant.js'

./~/prop-types/~/fbjs/lib/warning.js

Module build failed: Error: ENOENT: no such file or directory, open 'node_modules\prop-types\node_modules\fbjs\lib\warning.js

**Comment by gaearon** [comment]
Please provide repository reproducing the issue.

**Comment by ljharb** [comment]
fbjs is no longer a dependency of prop-types.
