### ISSUE TITLE
prop-types doesn't validate props when using decorators

### ISSUE THREAD

**Issue by Tomekmularczyk** [facebook/prop-types#77]
Not sure is it a problem with babel decorators transpiling or with prop-types (or something else) but when I use decorators I don't get errors in console about types mismatch. Code below won't raise any errors about 'fetchPaymentStatus' not being a string:

![zrzut ekranu 2017-06-09 o 14 02 52](https://user-images.githubusercontent.com/12544704/26974607-5da160c6-4d1c-11e7-8ae3-34f6203bf17c.png)

It will however raise error about not supplying required attribute.

If this is required I can prepare some test repo.

**Comment by ljharb** [comment]
Isn't that because the connected component always supplies it? Iow it's a propType of the inner one, but not the outer one.

I'm not sure a decorator is the best thing to use here without also using class properties on the propTypes.

**Comment by Tomekmularczyk** [comment]
@ljharb not sure what you mean by "connected component always supplies it".

I created a branch with App component that you can look into if you're interested.
https://github.com/Tomekmularczyk/react-starter/tree/prop-types

I tried to use class properties before but with the same result.

**Comment by dubert** [comment]
I believe I am encountering the same issue. I'm using a HOC to style my component, and I get this error.

**Comment by barrymichaeldoyle** [comment]
I know this is an old issue, buy why don't you set the props types like this:

`
export default class extends React.Component {
  static propTypes = {
    something: PropTypes.string.isRequired,
    fetchPaymentStatus: PropTypes.string,
  }

  // rest
}
`
