### ISSUE TITLE
how to check what type does the checker function accept?

### ISSUE THREAD

**Issue by plantvsbirds** [facebook/prop-types#79]
I have a react component imported and its .propTypes available, i.e. a map of all prop names to their checker function. Now I would like to get their accepting types.

One way I can think of is to feed each checker function with some value and find out. It should work totally fine for native value. The other is to extend each checker's prototype and record expected type info. 

Is there a more proper and present way to do this?

**Comment by ljharb** [comment]
What's the use case? Note that because there are custom validators, and composition like `oneOfType`, there's no single "type" that a validator necessarily maps to.

**Comment by plantvsbirds** [comment]
I would like to doc a react component and really don't want to reclaim the type in jsdoc-formatted comment. I want to build a doc generator that automatically extract the type from certain component

**Comment by ljharb** [comment]
I don't think that's possible, for the reasons I gave above.

**Comment by plantvsbirds** [comment]
Yeah, I also tried to call directly, even with the classic secret. That
didn't work either. I guess I would just go back writing jsdoc comment

Jordan Harband <notifications@github.com>于2017年6月13日 周二23:54写道：

**Comment by plantvsbirds** [comment]
for anyone with similar goal, I suggest doing static analysis on your code. works pretty well, given prop-type's concise design.
