### ISSUE TITLE
errors after flow check

### ISSUE THREAD

**Issue by goornari** [facebook/prop-types#82]
Hi all, 
this issue are struggling me.

After a flow check there are these errors and i don0t know how to fix:

Library type error:
flow-typed/npm/prop-types_v15.x.x.js:11
 11:   declare var array: React$PropType$Primitive<Array<any>>;

Library type error:
flow-typed/npm/prop-types_v15.x.x.js:18
 18:   declare var arrayOf: React$PropType$ArrayOf;
                            ^^^^^^^^^^^^^^^^^^^^^^ identifier `React$PropType$ArrayOf`. Could not resolve name

Library type error:
flow-typed/npm/prop-types_v15.x.x.js:20
 20:   declare var instanceOf: React$PropType$InstanceOf;
                               ^^^^^^^^^^^^^^^^^^^^^^^^^ identifier `React$PropType$InstanceOf`. Could not resolve name

Library type error:
flow-typed/npm/prop-types_v15.x.x.js:22
 22:   declare var objectOf: React$PropType$ObjectOf;
                             ^^^^^^^^^^^^^^^^^^^^^^^ identifier `React$PropType$ObjectOf`. Could not resolve name

Library type error:
flow-typed/npm/prop-types_v15.x.x.js:23
 23:   declare var oneOf: React$PropType$OneOf;
                          ^^^^^^^^^^^^^^^^^^^^ identifier `React$PropType$OneOf`. Could not resolve name

Library type error:
flow-typed/npm/prop-types_v15.x.x.js:24
 24:   declare var oneOfType: React$PropType$OneOfType;
                              ^^^^^^^^^^^^^^^^^^^^^^^^ identifier `React$PropType$OneOfType`. Could not resolve name

Library type error:
flow-typed/npm/prop-types_v15.x.x.js:25
 25:   declare var shape: React$PropType$Shape;
                          ^^^^^^^^^^^^^^^^^^^^ identifier `React$PropType$Shape`. Could not resolve name

**Comment by ljharb** [comment]
This seems like an issue that needs to be filed on flow-typed.
