### ISSUE TITLE
`instanceOf` not working when testing with Jest and Enzyme

### ISSUE THREAD

**Issue by dgrcode** [facebook/prop-types#83]
I'm working on an chat app where I use WebSockets. The code of one of the components is the following:

```javascript
// ChatView.js
'use strict';

import React from 'react';
import PropTypes from 'prop-types';

export default class ChatView extends React.Component {
  static propTypes = {
    ws: PropTypes.instanceOf(WebSocket).isRequired
  }

  handleSend = (message) => {
    // it is here where I need to use the WebSocket connection
  }

  render () {
    //...
  }
}
```

And I'm using the following unit test file for testing with Jest and Enzyme:
```javascript
// ChatView.test.js
'use strict';
/* global describe, expect */

global.WebSocket = function () {
  this.send = (message) => console.log('message sent:', message);
};

import React from 'react';
import { shallow } from 'enzyme';
import ChatView from '../../src/client/components/ChatView';

describe('The ChatView component', () => {
  const component = shallow(<ChatView ws={new global.WebSocket()}/>);
  // tests here
});
```

Here I'm getting a `ReferenceError`:
```bash
ReferenceError: WebSocket is not defined
      
      at Object.<anonymous> (src/client/components/ChatView.js:28:114)
      at Object.<anonymous> (test/unit_tests/ChatView.test.js:10:17)
```

According to React documentation:
 > // You can also declare that a prop is an instance of a class. This uses
  // JS's instanceof operator.

So I've checked myself by using the following render method for the `ChatView` component:
```javascript
render () {
    return (
      <div>
        {(this.props.ws instanceof WebSocket).toString()}
      </div>
    );
  }
```

The result of the render is the string `true`, so I assume that the component has access to both `this.props.ws` and `WebSocket`, and that the instance of `this.props.ws` is `WebSocket`. For some reason when I make a reference inside `propTypes` declaration, it doesn't have access to `WebSocket`.

Am I missing something? Is this the expected behavior?

**Comment by ljharb** [comment]
`import`s are hoisted to the top - so they're being parsed *before* your global WebSocket shim

In other words, you'd need to import your WebSocket shim, so that it will be ran before ChatView.

**Comment by dgrcode** [comment]
@ljharb That was the reason behind the issue. Thanks for clarifying it.

For others that could face the same problems, what I did to solve it, taking into account that `import`s are hoisted, is the following:

```javascript
// ChatView.test.js
'use strict';
/* global describe, expect */

import { WebSocket } from '../dummyWebSocket';

import React from 'react';
import { shallow } from 'enzyme';
import ChatView from '../../src/client/components/ChatView';

describe('The ChatView component', () => {
  const component = shallow(<ChatView ws={new WebSocket()}/>);
  // tests here
});
```

Being `dummyWebSocket.js` the following file:
```javascript
// dummyWebSocket.js
'use strict';

export function WebSocket () {
  this.send = function (message) {
    console.log('sent message:', message);
  };
}

global.WebSocket = WebSocket;
```

**Comment by ljharb** [comment]
(I'd recommend not exporting anything from your shim file; generally you want side-effecting code to be separate from value-providing code. ie, `import '../dummyWebSocket';` alone)

**Comment by dgrcode** [comment]
Thanks for the tip!

Would you say that I should do something like this then?

```javascript
// dummyWebSocket.js
'use strict';

export default function WebSocket () {
  this.send = function (message) {
    console.log('sent message:', message);
  };
}
```

```javascript
// dummyWebSocketInjector.js
'use strict';
import WebSocket from './dummyWebSocket';

global.WebSocket = WebSocket;
```

```javascript
// ChatView.test..js
'use strict';
import './dummyWebSocketInjector';
import WebSocket from './dummyWebSocket';

//...
```

**Comment by ljharb** [comment]
yes.
