### ISSUE TITLE
Is it possible to disallow properties not defined in Component.propTypes?

### ISSUE THREAD

**Issue by croraf** [facebook/prop-types#84]
If i have the following properties definition, and I pass a property `onMove `to the component it will not throw error or warning. Is it possible to disallow properties not defined in Component.propTypes?
```
Component.propTypes = {
    onClick: PropTypes.func,
    rejected: PropTypes.bool
};
```

**Comment by ljharb** [comment]
Use PropTypes.exact, or the `prop-types-exact` package.

**Comment by aweary** [comment]
👍 , but a heads up that `ProTypes.exact` was [temporarily reverted](https://github.com/facebook/prop-types/pull/80) due to some missing infrastructure, but should be back soon and in the next release.

**Comment by croraf** [comment]
Can you show example of usage, or refer to example, because I cannot find it in documentation?

**Comment by ljharb** [comment]
#87 re-added `exact` including docs for it.
