### ISSUE TITLE
InstanceOf list with specific type of objects

### ISSUE THREAD

**Issue by ldrahnik** [facebook/prop-types#89]
I was expecting to be able to use `PropTypes.instanceOf` to specify immutable list with specific objects:

```
selectedOptions: PropTypes.instanceOf(List<SelectedSelectOption>())
```

But i get warning:

```
warning.js:36 Warning: Failed prop type: Right-hand side of 'instanceof' is not callable
```

What i do wrong?

**Comment by ljharb** [comment]
Try removing the ()? instanceOf takes a constructor, not an instance.
