### ISSUE TITLE
Migrating from React.PropTypes

### ISSUE THREAD

**Issue by MirTalpur** [facebook/prop-types#97]
```
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```
I had the above warning show up so I decided to migrate from using React.PropTypes.
While using React.propTypes I had
```
static contextTypes = {
  router: React.PropTypes.object,
};
```
Which worked out perfectly but using
```
import PropTypes from 'prop-types';
static contextTypes = {
  router: PropTypes.object,
};
```

```
TypeError: Cannot read property 'object' of undefined
```
Gives me an object is undefined error? Any idea how I can fix this?

**Comment by ljharb** [comment]
What's your question?

**Comment by avigil06** [comment]
I had a similar thing happen to me. When I tried to migrate from React.PropTypes to prop-types library, PropTypes was undefined.

I am also wondering how I move forward migrating to the prop-types library if PropTypes is undefined.

**Comment by ljharb** [comment]
It shouldn't be; if you're getting `undefined` there then either you need to `npm install prop-types`, or there's something broken about your build process.

**Comment by MirTalpur** [comment]
thanks @ljharb after investigating this further I realized my build did not support ```prop-types``` and that was what was causing me to get the ```undefined``` error.

**Comment by avigil06** [comment]
@MirTalpur I am a new team member in an existing React Project. We use Webpack to manage our build pipeline. Would you be able to point me in a direction of making sure our pipeline supports prop-types? I haven't been able to determine which part of the webpack needs to be investigated.

**Comment by MirTalpur** [comment]
Hey @avigil06 I can only answer for our case and we were using Typescript and we weren't using the latest Typescript version and for some reason prop-types wasn't working well with our version of Typescript. Upgrading typescript and some other libraries fixed our issue.
